### ISSUE TITLE
Notation in creating the context vector

### ISSUE THREAD

**Issue by graviraja** [bentrevett/pytorch-seq2seq#10]
Hi, thanks for your writing.

In the Neural Machine Translation by Jointly Learning to Align and Translate notebook, while creating the context vector Z you said the equation is
![screen shot 2019-02-02 at 10 04 07 pm](https://user-images.githubusercontent.com/7556119/52166467-be3d1400-2733-11e9-972e-804fd86e5e81.png)

Previously, for stacking you used the following

![screen shot 2019-02-02 at 10 04 18 pm](https://user-images.githubusercontent.com/7556119/52166473-d876f200-2733-11e9-8deb-d4b4c6049f66.png)

Do you mean to take the final hidden state of forward(hT, computed after seeing input xt) and final backward hidden state(hT, computed after seeing input x1)
(or) final hidden states of forward(hT, computed after seeing input xt) and inital backward hidden state(h1, computed after seeing input xt)?

**Comment by bentrevett** [comment]
We pass the final hidden state of the forward (h_T^fwd, after seeing x_T) and the final hidden state of the backward (h_T^bck, after seeing x_1). 

Using the stacking notation, it's the backward RNN part of h_1 (h_T^bck), and the forward RNN part of h_T (h_T^fwd).
