### ISSUE TITLE
Tutorial 4: Question about about packed padded sequences

### ISSUE THREAD

**Issue by kushalj001** [bentrevett/pytorch-seq2seq#101]
In tutorial 4, packed padded sequences are not used on the decoder side. Is there any specific reason for doing so?
Thank you.

**Comment by bentrevett** [comment]
The main reason to used packed padded sequences is so we don't have to run our RNN/LSTM/GRU over padding tokens as it is basically wasted computation - a padding token contains no information that will help you translate a sentence. You can only really do this if you have the entire sequence beforehand.

We cannot do this when generating our predicted output sequence as we do not have the whole sequence at the beginning of the generation. We have the target sequence - what the output sequence should be - but there is no guarantee that the sequence output by the model will be exactly the same.
