### ISSUE TITLE
scale of skip connection

### ISSUE THREAD

**Issue by wizardk** [bentrevett/pytorch-seq2seq#104]
Hi, thanks for your clear and helpful tutorial.

I have a question that are the following two methods the same?

self.scale = torch.sqrt(torch.FloatTensor([0.5])).to(device)
self.scale = math.sqrt(.5)

**Comment by bentrevett** [comment]
Yes, they should be the same. I should get around to changing that.

**Comment by wizardk** [comment]
@bentrevett thanks a lot.
