### ISSUE TITLE
Tutorial 6: How to fit in pre-trained embedding matrix as the embedding layer in the transformer model?

### ISSUE THREAD

**Issue by Ninja16180** [bentrevett/pytorch-seq2seq#105]
Thanks Ben for your wonderful tutorial on the attention mechanism.

We are trying to build a conversational model based on transformer principle.
One of our main objectives for the conversational model is to maximise the coverage of our training vocabulary by word vectors from pre-trained word embeddings.
Thus we are planning to use multiple pre-trained word embeddings like : glove, gensim, fasttext to serve our purpose of ensuring maximum coverage.

But, there remains this gap in understanding : how to implement this/fit this in to the transformer model you taught to build in the 6th tutorial?

I am attaching here with a jupyter notebook which contains blocks of codes to give an idea of the requirement we are struggling to meet.

It will be really helpful if you could shed some light on how to achieve our goal.
Thanks in adance!
[Approach.zip](https://github.com/bentrevett/pytorch-seq2seq/files/4555264/Approach.zip)

**Comment by bentrevett** [comment]
Is there any chance you could upload the notebook to a GitHub gist?

**Comment by bentrevett** [comment]
I have detailed one way to add pre-trained embeddings to a Torchtext vocabulary [here](https://github.com/pytorch/text/issues/722#issuecomment-609880042). 

So as long as you can write the embeddings to a file, they should be easy to load with Torchtext. I have not seen of many people doing work in combining pre-trained embeddings using multiple sources though, would be interesting to see how it works.

**Comment by Ninja16180** [comment]
Thanks Ben!
I will try this out and will keep you posted on how it goes.
We might require your help along the way to complete this activity.

For the time being thus keeping this issue open

**Comment by Ninja16180** [comment]
Hi Ben,

I have preprocessed my data today and created a custom_embedding dictionary.
The dictionary contains a word and corresponding word vector and it has been constructed following this logic:
I have referred two pretrained embeddings and for each unique word in my dataset I looked up in both the pre-trained embeddings for word vector and if neither of the embeddings has that word I have filled in the value part with a vector of same embedding size containing random values.

However, I would like to ask for your help to convert this dictionary to the following format (which you suggested):
"The format of your custom_embeddings.txt file needs to be the token followed by the values of each of the dimensions for 
the embedding, all separated by a single space, e.g. here's three tokens with 20 dimensional embeddings (all just ones as an example):

good 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
great 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
awesome 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0"

I have uploaded my code so far in this git repo for your review.
https://github.com/Ninja16180/Rough_Transformer/blob/master/Rough_Transformer2.ipynb

It will be really helpful if you could guide how to save the dictionary in the very format you suggested?

Thanks in advance!

**Comment by bentrevett** [comment]
All you need to do with your `cust_embedding` is write it to a .txt file which Torchtext can then read and turn into a `Vectors` object.

This can be done with:
```python
with open('custom_embeddings.txt', 'w+') as f:
    for token, vector in cust_embedding.items():
        vector_str = ' '.join([str(v) for v in vector])
        f.write(f'{token} {vector_str}\n')
```

The rest of the steps linked in the issue can then be followed:
```python
import torchtext.vocab as vocab
custom_embeddings = vocab.Vectors(name = 'custom_embeddings.txt')
TEXT.build_vocab(train_data, vectors = custom_embeddings)
model.embedding.weight.data.copy_(TEXT.vocab.vectors)
```

Let me know if that works for you.

**Comment by Ninja16180** [comment]
Thanks a lot Ben!
Let me try this.
I will keep you posted on the progress.

**Comment by Ninja16180** [comment]
Hi Ben,

I have created custom embedding as suggested by you.
Also add the following line to both the Encoder and Decoder classes:

self.tok_embedding = nn.Embedding(input_dim, hid_dim)

        # step added for custom embedding
        self.tok_embedding.weight.data.copy_(custom_embeddings)

        self.pos_embedding = nn.Embedding(max_length, hid_dim)

However, while building the encoder object the following error was thrown.

TypeError                                 Traceback (most recent call last)
<ipython-input-72-06d3631c029b> in <module>()
     18               ENC_PF_DIM,
     19               ENC_DROPOUT,
---> 20               device)
     21 
     22 dec = Decoder(OUTPUT_DIM, 

<ipython-input-59-6c2f23451d01> in __init__(self, input_dim, hid_dim, n_layers, n_heads, pf_dim, dropout, device, max_length)
     16 
     17         # step added for custom embedding
---> 18         self.tok_embedding.weight.data.copy_(custom_embeddings)
     19 
     20         self.pos_embedding = nn.Embedding(max_length, hid_dim)

TypeError: copy_(): argument 'other' (position 1) must be Tensor, not Vectors
------------------------------
The git repo is updated with the latest file with error description for your reference:
https://github.com/Ninja16180/Rough_Transformer/blob/master/Rough_Transformer_v.03.ipynb

Could you please advice, what went wrong ang and how to fix the issue?
Thanks in advance!

**Comment by bentrevett** [comment]
As mentioned in my previous code snippet, you cannot `.copy_` from the `custom_embeddings` as it is a `Vectors` object and not a tensor.

Assuming you are using `sent1` as the source and `sent2` as the target, then encoder you should have:

```python
self.tok_embedding.weight.data.copy_(sent1.vocab.vectors)
```

The decoder should also be changed to:

```python
self.tok_embedding.weight.data.copy_(sent2.vocab.vectors)
```

**Comment by Ninja16180** [comment]
Thanks Ben! It did resolved the issue.
My bad, I missed to understand the implication of using TEXT.vocab.vectors with copy_.

I am now able to proceed till training the model; I will keep you posted.
I am really grateful for your help along the way whenever I got stuck with any issue.
Thanks again!

**Comment by Ninja16180** [comment]
Also I am closing this issue as I am now able to suceessfully use pre-trained embedding matrix in my model.

**Comment by Ninja16180** [comment]
Also I am closing this issue as I am now able to suceessfully use pre-trained embedding matrix in my model.
For any other query (if I come across) I will open a new issue.
Thanks!
