### ISSUE TITLE
Multi30k.splits for French is throwing error

### ISSUE THREAD

**Issue by summa10-git** [bentrevett/pytorch-seq2seq#109]
Thanks for your blogs; they are very informative.

I wanted to build French to English translator.

Creation of Fields object for french language did not throw any error.

`spacy_fr = spacy.load('fr')`

```
def tokenize_fr(text):
    """
    Tokenizes French text from a string into a list of strings
    """
    return [tok.text for tok in spacy_fr.tokenizer(text)]
```
```
SRC = Field(tokenize = tokenize_fr, 
            init_token = '<sos>', 
            eos_token = '<eos>', 
            lower = True, 
            batch_first = True)
```
--------------------------------------------------------------------------------------------
But splitting the dataset is throwing error:
`train_data, valid_data, test_data = Multi30k.splits(exts = ('.fr', '.en'),fields = (SRC, TRG))`

Error:

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-82f598bd2264> in <module>()
      1 train_data, valid_data, test_data = Multi30k.splits(exts = ('.fr', '.en'), 
----> 2                                                     fields = (SRC, TRG))

2 frames
/usr/local/lib/python3.6/dist-packages/torchtext/datasets/translation.py in __init__(self, path, exts, fields, **kwargs)
     32 
     33         examples = []
---> 34         with io.open(src_path, mode='r', encoding='utf-8') as src_file, \
     35                 io.open(trg_path, mode='r', encoding='utf-8') as trg_file:
     36             for src_line, trg_line in zip(src_file, trg_file):

FileNotFoundError: [Errno 2] No such file or directory: '.data/multi30k/train.fr'
```
-------------------------------------------

While trying without the `exts` argument throws another error saying this is the required argument.
`TypeError: splits() missing 1 required positional argument: 'exts'`

Any idea how to split dataset for French?

**Comment by bentrevett** [comment]
Looks like TorchText doesn't actually download the training and validation French data at all for some reason.

You can manually download each of them from [here](https://github.com/multi30k/dataset/blob/master/data/task1/raw/train.fr.gz) and [here](https://github.com/multi30k/dataset/blob/master/data/task1/raw/val.fr.gz). Extract and place them in the /multi30k folder with the rest of the data and it all should work fine.

**Comment by summa10-git** [comment]
Thank you.
This resolved the issue
