### ISSUE TITLE
Tutorial 6: How to modify the size of custom embedding? related to issue#105

### ISSUE THREAD

**Issue by Ninja16180** [bentrevett/pytorch-seq2seq#112]
Hi Ben,

You helped me in implementing custom embedding for my transformer model.
Giving below the issue link for reference:
https://github.com/bentrevett/pytorch-seq2seq/issues/105

I have used pre-trained matix of dimension 300 for my model.
crawl-300d-2M.vec
glove.6B.300d.txt

However I want to resize the embedding dimension to 256 so that it can be at par with the Hidden Dimension of 256 I want to use for my model.

I used the following function to limit the size of the pretrained embedding matrix to 256:

```
def load_embedding(embedding_file):
    
    def get_coefs(word,*arr): 
      return word, np.asarray(arr, dtype='float32')[:256]  # keeping the embedding size 256

    embeddings_index = dict(get_coefs(*o.split(" ")) for o in open(embedding_file, encoding="utf8", errors='ignore') if len(o)>100)

    return embeddings_index
```

And I checked that it is successfully limiting the pretrained embedding size to 256.

Next I created custom embedding matrix likewise:

```
# creating a placeholder embedding matrix first

all_embs = np.stack(fasttext_embeddings_index.values())  
emb_mean,emb_std = all_embs.mean(), all_embs.std()
embed_size = all_embs.shape[1]

nb_words = len(word_index)
embedding_matrix = np.random.normal(emb_mean, emb_std, (nb_words, embed_size))
```
I checked the size of the embedding_matrix at this point and found the size to be 256.

Next I created custom embedding
```
# custom embedding creation which is a dictionary containing word and corresponding word vector

cust_embedding = {}

for word, indx in word_index.items():
  if indx < nb_words:
    embedding_vector = fasttext_embeddings_index.get(word) 
    if embedding_vector is None:
      embedding_vector = glove_embeddings_index.get(word) 
    if embedding_vector is None:
      embedding_vector = embedding_matrix[indx]

    cust_embedding[word] = embedding_vector
```
 Next this dictionary has been saved to a .txt file named custom_embeddings.txt.

but when I am creating a torchtext.vocab.Vectors object with this custom embedding file, I could see the size is 300.

I tried modifying the size by using max_size argument ( as I have read about this argument in the torchtext.vocab.Vectors documentation) 
`custom_embeddings = vocab.Vectors(name = '/content/drive/My Drive/Data/custom_embeddings.txt', max_size= 256)`

But that threw error :
`TypeError: __init__() got an unexpected keyword argument 'max_size'`

However, I think this size needes to be modified to 256 as otherwise during training I am getting this error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-75-d4dd8304c0ad> in <module>()
     20               ENC_PF_DIM,
     21               ENC_DROPOUT,
---> 22               device)
     23 
     24 dec = Decoder(OUTPUT_DIM, 

<ipython-input-67-f239fb126b0e> in __init__(self, input_dim, hid_dim, n_layers, n_heads, pf_dim, dropout, device, max_length)
     18 
     19         # step added for custom embedding
---> 20         self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)
     21 
     22         self.pos_embedding = nn.Embedding(max_length, hid_dim)

RuntimeError: The size of tensor a (256) must match the size of tensor b (300) at non-singleton dimension 1
```
For your reference giving below the values set for training the model:

```
INPUT_DIM = len(ENC_TEXT.vocab)
OUTPUT_DIM = len(DEC_TEXT.vocab)
HIDDEN_DIM = 256  # size of each pretrained word vector in the embedding matrix ie size[1] of the embedding matrix
ENC_LAYERS = 3
DEC_LAYERS = 3
ENC_HEADS = 10
DEC_HEADS =10
ENC_PF_DIM = 512 
DEC_PF_DIM = 512 
ENC_DROPOUT = 0.1
DEC_DROPOUT = 0.1

enc = Encoder(INPUT_DIM, 
              HIDDEN_DIM , 
              ENC_LAYERS, 
              ENC_HEADS, 
              ENC_PF_DIM, 
              ENC_DROPOUT, 
              device)

dec = Decoder(OUTPUT_DIM, 
              HIDDEN_DIM , 
              DEC_LAYERS,
              DEC_HEADS, 
              DEC_PF_DIM, 
              DEC_DROPOUT, 
              device)
```

Please let me know if modifying the cusom_embedding's dimension to 256 would resolve this runtime error?
and if so, pls advice how to modify the size of torchtext.vocab.Vectors object.

I think if this bit is done, the fine tuning of my model's hyper parameter will be lot more easier and my model would produce better output.

Really appreciate your help to resolve this part.

Thanks in advance!

**Comment by bentrevett** [comment]
The problem is that your pre-trained embeddings are tuned to be 300-dimensions. They are trained to make full use of all 300-dimensions in the embedding vector space. Slicing these trained vectors to 256-dimensions effectively throws away 44-dimensions worth of "information" and I don't think that's a good idea.

I don't think it is necessary to re-size the pre-trained embeddings, I would instead picked the hyperparameters of the model appropriately based on the 300-dimensional embeddings.

If you are adamant about re-sizing the embeddings to 256-dimensions then I would instead do something similar to [this paper](https://nlp.stanford.edu/pubs/snli_paper.pdf) where they add a "translation layer" - just a `nn.Linear` layer - after the embeddings which projects it down to a lower dimensionality. In your case that would simply be `self.translation = nn.Linear(300, 256)` and then use this after the embeddings are calculated as:

```python
# in the encoder
src = self.dropout((self.tok_embedding(src) * self.scale) + self.pos_embedding(pos))
src = self.translation(src)
```

```python
# in the decoder
trg = self.dropout((self.tok_embedding(trg) * self.scale) + self.pos_embedding(pos))
trg = self.translation(trg)
``` 

This way you are not simply just chucking away 44-dimensions worth of information, but your model actually learns to compress 300-dimensions down into 256-dimensions by disregarding irrelevant information in the embeddings.

**Comment by Ninja16180** [comment]
Thanks Ben for the clarification.
I would like to try both the options(keeping embedding size 300 and compressing the size to 256) to see with which my model works better.

I first tried by compressing the dimension.

Here is the code snippet for your reference -- the new lines of code added in the Encoder class(accordingly changes were made to the decoder class too):

```
# removed a chunk of codes in here and only showing the modified/newly added lines
class Encoder(nn.Module):
    def __init__(self, 
                 input_dim, 
                 hid_dim, 
                 n_layers, 
                 n_heads, 
                 pf_dim,
                 dropout, 
                 device,
                 max_length = 100):
                 
        super().__init__()

        self.device = device
        
        self.tok_embedding = nn.Embedding(input_dim, hid_dim)

        # step added for custom embedding
        self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)

        self.pos_embedding = nn.Embedding(max_length, hid_dim)
        
        # step added to compress embedding dimension size from 300 to 256
        self.translation = nn.Linear(300, 256)

    def forward(self, src, src_mask):
        
              
        src = self.dropout((self.tok_embedding(src) * self.scale) + self.pos_embedding(pos))

        # step added to compress embedding dimension size from 300 to 256
        src = self.translation(src)
        
                    
        return src
```

However I am still getting the same error while initialising the parameters:


```
INPUT_DIM = len(SRC.vocab)
OUTPUT_DIM = len(RESP.vocab)
HID_DIM = 256  # size of each pretrained word vector in the embedding matrix ie size[1] of the embedding matrix
ENC_LAYERS = 3
DEC_LAYERS = 3
ENC_HEADS = 10
DEC_HEADS =10
ENC_PF_DIM = 512 
ENC_DROPOUT = 0.1
DEC_DROPOUT = 0.1

enc = Encoder(INPUT_DIM, 
              HID_DIM, 
              ENC_LAYERS, 
              ENC_HEADS, 
              ENC_PF_DIM, 
              ENC_DROPOUT, 
              device)

dec = Decoder(OUTPUT_DIM, 
              HID_DIM, 
              DEC_LAYERS,
              DEC_HEADS, 
              DEC_PF_DIM, 
              DEC_DROPOUT, 
              device)
```
Error:
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-80-d4dd8304c0ad> in <module>()
     20               ENC_PF_DIM,
     21               ENC_DROPOUT,
---> 22               device)
     23 
     24 dec = Decoder(OUTPUT_DIM, 

<ipython-input-73-b398396d6eff> in __init__(self, input_dim, hid_dim, n_layers, n_heads, pf_dim, dropout, device, max_length)
     18 
     19         # step added for custom embedding
---> 20         self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)
     21 
     22         self.pos_embedding = nn.Embedding(max_length, hid_dim)

RuntimeError: The size of tensor a (256) must match the size of tensor b (300) at non-singleton dimension 1
```
Not sure what is this tensor b? and why its dimension remains unaltered?
As per my understanding both the tensors i.e input to encoder and decoder has dimension 256. Not sure if my understanding is wrong.

**Comment by Ninja16180** [comment]
Also, if I would go with not altering the size of the embedding matrix and keep it 300, then during hyper parameter tuning what would be a good choice of values for the hidden layer?

A multiple of 300?
hid_dim = random.choice([150, 300, 600, 900])

Thanks in advance.

**Comment by bentrevett** [comment]
Your error is because you have `hid_dim` (the output of your embeddings) to 256 but you are trying to load pre-trained embeddings that have 300 dimensions. Your pre-trained embeddings always need to be the same size as the embedding vectors output by the embedding layer. 

In a transformer, the `hid_dim` is the same as your embedding dim. If you are using 300 dimensional embeddings then your `hid_dim` should always be 300. It's a bit confusing because most translation models, such as RNNs, have an `embedding_dim` and a `hidden_dim`, which can be different. In transformer models they must be the same, hence why they actually use the term `model_dim` in the paper instead of `hid_dim`. 

Saying all of that, if you are going to use the translation layer and compress the 300 dimensional embeddings to 256 dimensions then `hid_dim` would now need to be 256 as this will be the size of the embeddings passed all around the model.

**Comment by Ninja16180** [comment]
Hi Ben, 
Thanks for explaining elaborately why I was getting the error in the first palce.

But after you told about option to compress the embedding dimension, I tried it likewise.
Here is the code snippet from encoder class where new lines of code added for dimension compression (did likewise to the decoder class as well)


class Encoder(nn.Module):
    def __init__():
        # step added to compress embedding dimension size from 300 to 256
        self.translation = nn.Linear(300, 256)

    def forward(self, src, src_mask):
        src = self.dropout((self.tok_embedding(src) * self.scale) + self.pos_embedding(pos))

        # step added to compress embedding dimension size from 300 to 256
        src = self.translation(src)


Next I initiated the hidden dimension with a value =256

INPUT_DIM = len(SRC.vocab)
OUTPUT_DIM = len(RESP.vocab)
`HID_DIM = 256`  
ENC_LAYERS = 3
DEC_LAYERS = 3
ENC_HEADS = 10
DEC_HEADS =10
ENC_PF_DIM = 512 
DEC_PF_DIM = 512
ENC_DROPOUT = 0.1
DEC_DROPOUT = 0.1

But still I received error
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-80-d4dd8304c0ad> in <module>()
     20               ENC_PF_DIM,
     21               ENC_DROPOUT,
---> 22               device)
     23 
     24 dec = Decoder(OUTPUT_DIM, 

<ipython-input-73-b398396d6eff> in __init__(self, input_dim, hid_dim, n_layers, n_heads, pf_dim, dropout, device, max_length)
     18 
     19         # step added for custom embedding
---> 20         self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)
     21 
     22         self.pos_embedding = nn.Embedding(max_length, hid_dim)

RuntimeError: The size of tensor a (256) must match the size of tensor b (300) at non-singleton dimension 1

I was talking about this error in my second response.

Not sure where it is going wrong or I am missing anything this time.
Thus shared the code snippet for your reference.

Also, another small advice I am looking for from you:

If I would go with not altering the size of the embedding matrix and keep it 300, then during hyper parameter tuning what would be a good choice of values for the hidden layer?

A multiple of 300?
hid_dim = random.choice([150, 300, 600, 900])

Thanks in advance.

**Comment by bentrevett** [comment]
By default the transformer's embedding dimension is equal to the hidden dimension. As you want your hidden dimension different to the embedding dimension, I would add an extra argument to the encoder and the decoder called `embedding_dim` and then change the `nn.Embedding` definitions in the encoder and decoder to:

```python
self.tok_embedding = nn.Embedding(input_dim, embedding_dim)
self.pos_embedding = nn.Embedding(max_length, embedding_dim)
```

You can then also change the translation layer to be:

```python
self.translation = nn.Linear(embedding_dim, hid_dim)
```

Then when defining the hyperparameters you can use `EMBEDDING_DIM = 300`. 

Those values of `hid_dim` look fine, you just need to try a few and see what works.

**Comment by Ninja16180** [comment]
Thank you so much for the solution.

I have made the code modification as per your advice.
And the error I was receiving earlier related to the mismatch in the size of embedding and hidden layers, is No more coming.

However, a strange error is now being thrown due to the mismatch in the `lengths of SRC.vocab and TRG.vocab`

I am giving below the code changes I made:

```
class Encoder(nn.Module):
    def __init__(self, 
                 input_dim,
                 **embedding_dim,** 
                 hid_dim, 
                 n_layers, 
                 n_heads, 
                 pf_dim,
                 dropout,
                 device,
                 max_length = 100):
                 
        super().__init__()

        self.device = device

        self.tok_embedding = nn.Embedding(input_dim, embedding_dim)

        # step added for custom embedding
        self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)

       self.pos_embedding = nn.Embedding(max_length, embedding_dim)
        
       
        self.translation = nn.Linear(embedding_dim, hid_dim)

    def forward(self, src, src_mask):
          
        batch_size = src.shape[0]
        src_len = src.shape[1]
        
        pos = torch.arange(0, src_len).unsqueeze(0).repeat(batch_size, 1).to(self.device)
        
        src = self.dropout((self.tok_embedding(src) * self.scale) + self.pos_embedding(pos))

        src = self.translation(src)
       
        for layer in self.layers:
            src = layer(src, src_mask)
                    
        return src
```
```
class Decoder(nn.Module):
    def __init__(self,
                 output_dim,
                 **embedding_dim,** 
                 hid_dim, 
                 n_layers, 
                 n_heads, 
                 pf_dim, 
                 dropout, 
                 device,
                 max_length = 100):
        super().__init__()
        
        self.device = device
        
        self.tok_embedding = nn.Embedding(output_dim, embedding_dim)

        self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)

        self.pos_embedding = nn.Embedding(max_length, embedding_dim)
               
        # step added to compress embedding dimension size from 300 to 256
        self.translation = nn.Linear(300, 256)
       
    def forward(self, trg, enc_src, trg_mask, src_mask):
                   
        batch_size = trg.shape[0]
        trg_len = trg.shape[1]
        
        pos = torch.arange(0, trg_len).unsqueeze(0).repeat(batch_size, 1).to(self.device)
           
        trg = self.dropout((self.tok_embedding(trg) * self.scale) + self.pos_embedding(pos))

        trg = self.translation(trg)
               
        for layer in self.layers:
            trg, attention = layer(trg, enc_src, trg_mask, src_mask)
        
        output = self.fc_out(trg)
                    
        return output, attention
```
And did the initialisation likewise:
```
INPUT_DIM = len(SRC.vocab)
OUTPUT_DIM = len(TRG.vocab)
HID_DIM = 256 
EMBEDDING_DIM = 300
```
And received the following error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-87-af1156e67eaa> in <module>()
     31               DEC_PF_DIM,
     32               DEC_DROPOUT,
---> 33               device)

<ipython-input-86-7a9b17e0d7ea> in __init__(self, output_dim, embedding_dim, hid_dim, n_layers, n_heads, pf_dim, dropout, device, max_length)
     18 
     19         # step added for custom embedding
---> 20         self.tok_embedding.weight.data.copy_(SRC.vocab.vectors)
     21 
     22         # self.pos_embedding = nn.Embedding(max_length, hid_dim)

RuntimeError: The size of tensor a (24407) must match the size of tensor b (21102) at non-singleton dimension 0
```
Where 21102 is the length of my SRC.vocab and 24407 is the length of my TRG.vocab.

Earlier this mismatch in lengths never threw any error.

Even I checked these lengths for the Multi30k dataset used in tutorial 6 and could see there also these two lengths are not equal.

I have started finetuning the hyperparameters following the other option where I am not downsizing the dimension of the embedding layer from 300 to 256.

However, getting bit interested in having this approach of altering the embedding dimension work as well.
Kindly advice as per your convenience, what else can be done to get this code run without error.

Thanks in advance!
