### ISSUE TITLE
Regarding Concatenation of Hidden Encoder State

### ISSUE THREAD

**Issue by jpanaro** [bentrevett/pytorch-seq2seq#115]
Just wanted to say excellent tutorial, and thank you for this great resource.

I am currently creating a bidirectional seq2seq model without attention and using LSTMs instead of GRU. It is essentially the model form tutorial 1 but with the LSTM in the encoder set to bidirectional.

My question is, now that the first hidden and cell dimension is doubled, and the decoder was left alone and is not bidirectional, what is the appropriate way to handle the hidden and cell states to make sure we retain all of the information, but are also compatible in size to the decoder LSTM?

Here is my current solution however I am afraid this is not acceptable:
![Screenshot from 2020-06-04 17-42-10](https://user-images.githubusercontent.com/49861328/83813176-de177b80-a68a-11ea-9ad5-9f548685ce9e.png)

**Comment by bentrevett** [comment]
Your solution looks good to me - I'm assuming you're using 4 layers in your encoder and decoder?

The main ways I see bidirectional encoder w/ unidirectional decoder handled is either by summing the forward and backward for each RNN layer (what you're doing) or by concatenating the forward and backward together and feeding them through a linear layer and sometimes an activation function for each RNN layer (what is done in notebook 3 and 4).

**Comment by jpanaro** [comment]
Yes, 4 layers for both.

I did reference the 3rd notebook, but since I am locked in to using only LSTMs without attention or GRUs, I think I got a little too mixed up. Thanks for the help!
