### ISSUE TITLE
batching of sample with maxlength using 3 standard deviation length

### ISSUE THREAD

**Issue by thak123** [bentrevett/pytorch-seq2seq#117]
# ❓ Questions & Help

## Details
Ben, I need your help. I read somewhere that rather than making batches of approx equal length where in the sentences are grouped based on the their length, a more robust way is to mix the sentences and have new_max_length = 3* std_dev([seq_lens(batch)]) where the sequences are either padded or truncated based on this new_max_length value . this value makes the network more robust to over fitting. Also we can have different sentences being part of different mini batches during training.

Can this be implemented easily in PyTorch  ?

**Comment by bentrevett** [comment]
Sure, this can be done, assuming we have `return_lengths = True` in the field (see notebook 4) then we'll get batches of sequences and their lengths and then can do something with it.

```python
#sequences already padded to maximum length by the bucket iterator
src, src_len = batch.text #src = [seq len, bsz], src_len = [bsz]

#get new max length
max_length = int(3 * torch.std(src_len.float()))

#cut to new max length
src = src[:max_length]
```

However, is it actually correct? It seems to work fine if the lengths are well distributed within a batch, but what if you have a batch of sentences that are all the same length? The standard deviation of the lengths will be zero and then you're just cutting the sequences down to have zero length, which cannot be correct. 

Even if you have them pretty close together, you'll get a small std. A batch of 9 with lengths of [6,6,7,7,8,8,9,9,10,10] has a 3 * std of 4 - which means every single sequence is losing a lot of tokens.

Any chance you can link where you read this?

**Comment by thak123** [comment]
I will try to search it and paste the link. I read this approach on a Kaggle winner solution post where he played with this kind of max_length trick.

But I think you are correct. There is no point in dropping half of the sequences in the batch.
