### ISSUE TITLE
Comment misplaced

### ISSUE THREAD

**Issue by binishjoshi** [bentrevett/pytorch-seq2seq#120]
#encoder_outputs is all hidden states of the input sequence, back and forwards
#hidden is the final forward and backward hidden states, passed through a linear layer

I think the comments are little bit misplaced in this [Tutorial 3 - Neural Machine Translation notebook](https://github.com/bentrevett/pytorch-seq2seq/blob/master/3%20-%20Neural%20Machine%20Translation%20by%20Jointly%20Learning%20to%20Align%20and%20Translate.ipynb) (Seq2Seq class)

I think it should be the following instead of the comment above written in notebook:
#hidden is all hidden states of the input sequence, back and forwards
#encoder_outputs is the final forward and backward hidden states, passed through a linear layer

**Comment by bentrevett** [comment]
The comments are correct.

`encoder_outputs` is a tensor containing the hidden state across every single time-step, forwards and backward.

`hidden` is a tensor containing the final hidden state (i.e. the hidden state from the final time-step), forwards and backward.

**Comment by binishjoshi** [comment]
Thanks for the clarification.
