### ISSUE TITLE
Tutorial 6: Batch inference to speed up the translation

### ISSUE THREAD

**Issue by ruathudo** [bentrevett/pytorch-seq2seq#123]
In tutorial 6: attention is all you need, the translation function accept one sentence and predict the target by looping through each next word. This is very slow in case of having many sentences. Do you have any idea to speed up this process by predicting multiple sentences at once. 
Can it be integrated with beam search feature?
Thanks!

**Comment by bentrevett** [comment]
If you want to do a batch translation then I would have a list of sentences as strings, then tokenize each one to get a list with lists of strings, then for each you would have to numericalize, pad, and convert to a tensor and then decode individually.

I probably won't add this to the tutorials as it's something people can figure out on their own and I am not really aiming for peak efficiency production level code. 

I need to re-write all the tutorials for the new TorchText API so will definitely add distribution sampling/beam search and a few other things then!

**Comment by ruathudo** [comment]
Thanks, no problem. I figured out how to implement batch translation and distributed beam search. 
One more question, I see pytorch already implemented transformer module, are you planing to have another version which use that existing pytorch module instead of doing from the scartch like in tutorial 6?

**Comment by bentrevett** [comment]
I'd be interested to see your batch translation and distributed beam search implementations if they are available anywhere.

I'm planning to completely re-write the tutorials to coincide with the release of the new TorchText API. In the re-written tutorial 6 I will show how to write the Transformer from scratch and use the PyTorch nn modules.

**Comment by ReemxxxOsama** [comment]
@ruathudo 
could you please share how could you achived to make batch translation and distributed beam search implementations.
i would like to achive the same thing and i want some hints.
