### ISSUE TITLE
I can not import bleu score.

### ISSUE THREAD

**Issue by GlazeDonuts** [bentrevett/pytorch-seq2seq#125]
Whenever I try to import the bleu score module from torchtext, I get an error

![image](https://user-images.githubusercontent.com/27892015/89188586-7dd68480-d5bc-11ea-8e03-daf787d174a7.png)

I tried using NLTK for calculating the bleu score but that ends up giving me some "CUDA Error: Device Side Assert Triggered"

Please provide a fix.

Thank you.

**Comment by redionxhepa** [comment]
I think this has to do with the version of TorchText,try to get an appropriate version.In my case I am using the code in Google Colab and I download a different version of TorchText and re-run twice the cell which imports the bleu-score.In this way it works.So the idea check the version of TorchText ,the problem stems from that. Hopefully that helps!

**Comment by binishjoshi** [comment]
Like @redionxhepa said,
First run this
`!pip install --upgrade torchtext`
And then Runtime -> Restart and run all
