### ISSUE TITLE
Tutorial 3 : Aligment Model not the same as the paper

### ISSUE THREAD

**Issue by xxoospring** [bentrevett/pytorch-seq2seq#126]
This is the alignment model in paper which has three single layer MLP: v, W and U, but in Tutorial 3 implementations，we cat vector *S* and encoder output h, and pass them  through one MLP.  

<img src="https://user-images.githubusercontent.com/21218850/89390013-bd29e000-d738-11ea-868b-a5727f98a1b0.png" alt="image" style="zoom:50%;" />

**Comment by bentrevett** [comment]
Not sure how I messed this up. Will look into it further. Thanks for pointing it out.

**Comment by yipliu** [comment]
> This is the alignment model in paper which has three single layer MLP: v, W and U, but in Tutorial 3 implementations，we cat vector _S_ and encoder output h, and pass them through one MLP.
> 
> ![image](https://user-images.githubusercontent.com/21218850/89390013-bd29e000-d738-11ea-868b-a5727f98a1b0.png)

Hi xxoospring,
Could you share your code with the Tutorial 3
