### ISSUE TITLE
Tutorial 6: question about dimension of trg_mask and src_mask in forward() of Encoder/Decoder/EncoderLayer/DecorderLayer. 

### ISSUE THREAD

**Issue by byc1234** [bentrevett/pytorch-seq2seq#138]
I see the below dimensions in forward() of Encoder/Decoder/EncoderLayer/DecorderLayer. 
```
        #trg_mask = [batch size, trg len]
        #src_mask = [batch size, src len]
```

Shouldn't those be
```
        #trg_mask = [batch size, 1, trg len, trg len]
        #src_mask = [batch size, 1, 1, src len]
```

`forward()` of `Seq2Seq` passes the below masks into Encorder and Decoder.
```
        #src_mask = [batch size, 1, 1, src len]
        #trg_mask = [batch size, 1, trg len, trg len]
``

**Comment by Caixiaomeng** [comment]
pytorch doc says:
masked_fill_(mask, value)
    Fills elements of self tensor with value where mask is True. The shape of mask must be **broadcastable** with the shape of the underlying tensor.

**Comment by bentrevett** [comment]
Fixed now. Thanks.
