### ISSUE TITLE
Tutorial 6: using own data, CUBLAS status alloc failed

### ISSUE THREAD

**Issue by izaskr** [bentrevett/pytorch-seq2seq#139]
Thank you for the great tutorials. I want to use the code from Tutorial 6 on my own dataset. I load the data with the TranslationDataset class. I copied the model and hyperparameters from the tutorial.

At the beginning of training the following error is reported:
Traceback (most recent call last):
```
  File "main.py", line 261, in <module>
    train_loss = train(model, train_iter, optimizer, criterion, CLIP)
  File "main.py", line 220, in train
    loss.backward()
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

Is the problem coming from the data reader or the model? 

Versions:
OS: Linux
Python 3.6
Pytorch 1.4.0
Torchtext 0.5.0
CUDA 10.1

**Edit 1**: Running the original code from the tutorial in the above described specs raises no errors.

**Edit 2**: moving everything to CPU, a new error message revealed that there's a mismatch in the size of the positional embedding layer and the sequence (?).

```
Traceback (most recent call last):
  File "main.py", line 266, in <module>
    train_loss = train(model, train_iter, optimizer, criterion, CLIP)
  File "main.py", line 215, in train
    output, _ = model(src, trg[:, :-1])
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/local/home/CE/skr/chart_descriptions/models/pytorch/model_components.py", line 315, in forward
    output, attention = self.decoder(trg, enc_src, trg_mask, src_mask)
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/local/home/CE/skr/chart_descriptions/models/pytorch/model_components.py", line 212, in forward
    trg = self.dropout((self.tok_embedding(trg) * self.scale) + self.pos_embedding(pos))
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/CE/skr/.conda/envs/torch14py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 100 out of table with 99 rows. at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

**Edit 3**: Apparently some of the sequences in my dataset are longer than 100 tokens. I fixed the maximum length to 100 in the definitions of the source and target Field. This fixed the issue. 

```
MAX_LEN = 100
SRC = Field(tokenize = tokenize_src,
            init_token = '<sos>',
            eos_token = '<eos>',
            lower = True,
            batch_first = True, use_vocab=True, fix_length=MAX_LEN)

TRG = Field(tokenize = tokenize_tg,
            init_token = '<sos>',
            eos_token = '<eos>',
            lower = True,
            batch_first = True, sequential=True, use_vocab=True, fix_length=MAX_LEN)
```

**Comment by bentrevett** [comment]
Yeah, some of the CUDA errors are a bit vague and changing your model to use the CPU gives more precise error messages.

As you've discovered, the issue is that the positional embedding layer only has 100 rows, i.e. only supports sequences up to 100 tokens long, and will throw an error if you try and feed it a sequence with >100 tokens. 

Setting `fix_length` will force all sequences to be `MAX_LEN`, this means sequences shorter than `MAX_LEN` will be padded and sequences longer than `MAX_LEN` will be trimmed. This is fine, but if you have a lot of short sequences then it adds a considerable amount of padding, which is why I don't like using `fix_length`.

I think a better solution would be to edit the `tokenize_src` and `tokenize_trg` to accept a `max_length` argument which just trims sequences longer than a given maximum length, i.e.:

```python
def tokenize_src(s, max_length):
    tokens = tokenize_fn(s)
    return tokens[:max_length]
```

This means you don't throw the error for sequences that are too long and you don't add a lot of unnecessary padding to short sequences.

**Comment by bentrevett** [comment]
Another thing to mention is that you should also think about your data. A good idea is to plot a histogram of how many tokens are in your examples. If you see the majority of your examples are between 100-200 tokens long, then you should probably increase the `max_length` argument of the `Encoder` and `Decoder` to be 200 or so.

**Comment by Yuvaraj91** [comment]
@bentrevett what is the way to get the number of tokens? Is it possible from `src_field.vocab.itos`?
