### ISSUE TITLE
Decoding in conv seq2seq

### ISSUE THREAD

**Issue by thinkwee** [bentrevett/pytorch-seq2seq#14]
In the convolutional sequence to sequence learning, the decoder input should be masked or the conv kernel should be casual. The model can not see future information when doing incremental decoding.

I have problems when dealing with the teacher forcing problems in conv seq2seq so I found this repo for help. Will the full inference function realized in the future? Thx～

**Comment by bentrevett** [comment]
Yep, I do plan to implement inference into the conv seq2seq model. Hopefully will have some time during this week!

**Comment by thinkwee** [comment]
Thank you !
Also I noticed that in fairseq version of ConvSeq2seq they decode the whole sentence at a time and transform the convolution block to linear when infer, which is called [linearized_convolution](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/linearized_convolution.py).
 They also use [ConvTBC](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/conv_tbc.py) which is an alternative version of Conv1d to do temporal convolution without any mask operation, both in encoder and decoder.
I have no idea why they do so.
