### ISSUE TITLE
maybe a mistake in t6

### ISSUE THREAD

**Issue by bufuchangfeng** [bentrevett/pytorch-seq2seq#143]
t6 decoder layer
The second is how we actually feed the encoded source sentence, enc_src, into our decoder. In this multi-head attention layer the queries are the **decoder** representations and the keys and values are the **decoder** representations. Here, the source mask, src_mask is used to prevent the multi-head attention layer from attending to <pad> tokens within the source sentence. This is then followed by the dropout, residual connection and layer normalization layers.

should second decoder be encoder?

thanks for these awesome tutorials.

**Comment by bentrevett** [comment]
Yep, that was my mistake. Fixed now.
