### ISSUE TITLE
Tutorial 3: The input of Attention

### ISSUE THREAD

**Issue by yipliu** [bentrevett/pytorch-seq2seq#149]
Hi Ben, 
This is a wonderful tutorial for me and I find a trivial issue.
In tutorial 3 about Attention: "This will take in the previous hidden state of the decoder". I guess this is encoder not decoder. Is it right?

**Comment by bentrevett** [comment]
No, it should be decoder. At every step of decoding you calculate the attention vector using **all** encoder hidden states (what your input sentence is) and the previous decoder hidden state (what your target sentence is so far).

**Comment by Vikramsingh7458** [comment]
Hi Ben,
In addition to the above question, **"This will take in the previous hidden state of the decoder, $s_{t-1}$, and all of the stacked forward and backward hidden states from the encoder, $H$."** 

What you meant is forward and backward outputs of encoder not there hidden states?

**Comment by bentrevett** [comment]
@Vikramsingh7458 The outputs are the hidden states.
