### ISSUE TITLE
how to download de package

### ISSUE THREAD

**Issue by jwc19890114** [bentrevett/pytorch-seq2seq#15]
python -m spacy download de
this code always return runtime error

**Comment by bentrevett** [comment]
What is the runtime error? Are you sure you have spaCy installed?

**Comment by jwc19890114** [comment]
> What is the runtime error? Are you sure you have spaCy installed?

I'm sure, and the problem was solved...

**Comment by gusdnd852** [comment]
I have the same problem. how to solve it?

**Comment by gusdnd852** [comment]
if we use administrator privileges, they didn't make any error
