### ISSUE TITLE
Tutorial 1: understanding LSTM

### ISSUE THREAD

**Issue by harshraj22** [bentrevett/pytorch-seq2seq#151]
Hi @bentrevett , I had the following doubts regarding LSTM

1. I used to think that length of sentence (num of words in sentence) should be equal to num of cells (hidden dim) in Lstms. In that way, word_i would be fed to LstmCell_i while the forward pass. But recently I read that there is no relation between them. Now I am not able to understand/ imagine how the Lstm works in encoder. What happens when number of words in a sentence don't match with the number of LstmCells. does one LstmCell take multiple word as input ?

2. the Lstm in encoder, takes a batch of sentences as input, and produces the context vector (which stores info about the sentence), while for decoding the context and generating words during translation, we need to use a loop. if number of LstmCells is same in both, are few cells left unused in decoder ?

**Comment by bentrevett** [comment]
Hi @harshraj22, I see that you've closed this issue now, which hopefully means you've answered your own questions, but just in case anyone else has these same questions I'll answer them anyway.

1. The number of words in the sequence has nothing to do with the number of hidden cells. Each word passed into the LSTM produces a hidden state which is of size `hid_dim` (which is equal to the number of hidden cells). So if you have a `hid_dim` of 256 and 10 words in your sentence your encoder gives you 10 tensors, each of which has 256 dimensions, i.e. a [10, 256] tensor, if we are ignoring any batch dimension. The LSTM takes, as input, the current word, and the previous hidden and cell state. The LSTM then outputs a new hidden and cell state. Then, the next word is used as an input, and the hidden and cell states we just calculated are used as the input hidden and cell states. This repeats until every input word has been fed into the LSTM. As you can see, we are using a single LSTM - the same weights/parameters - for every time-step. 

2. The final hidden state from the encoder - the context vector - is used for the initial hidden state of the decoder. If the encoder and decoder both have the same `hid_dim`, then the context vector is used as the initial decoder hidden state without any modification, no cells are left unused. If your encoder and decoder had different `hid_dim` values then you would have to find a way to rectify this, the most common example is feeding the context vector through a linear layer that outputs a tensor of the decoder's `hid_dim` shape.

Let me know if this clarifies things.

**Comment by harshraj22** [comment]
Thanks @bentrevett , 
All of the things are clear now. 

Though, I would reframe the encoder - decoder question in case anyone else visits and doesn't understand what I had asked, as it seems a little vague.

suppose input to encoder is `[10, 120]` ie. a sentence of 10 words, each mapped to 120 dimentional embedding, to get context vector, we do something like the following:
```python
# not focusing on correct syntax for now
context = nn.Lstm(input)
```

so, if `hidden_dim` is 50, context will be `[10, 50]`. It seems, it internally loops through the words of sentence, generates the corresponding hidden vectors, and feeds them as input for next word.

Now, in case of decoder (sentence generation), in most of the tutorial, I have seen the following kind of approach:
```python
for _ in range(req_sentence_len):
    next_word = Decoder(prev_word)
```
i.e. we manually write a loop to generate the words one by one passing it through the decoder lstm (kindly ignore the hidden dimention details for decoder). The question is, if Lstm in encoder can loop through words, feeding each previous word and corresponding hidden state itself, why can't the decoder do that internally, rather than us having to do it in a for-loop manually.

**Comment by bentrevett** [comment]
We don't have to do an explicit `for` loop in the encoder because we already have the entire sequence we are going to process with our LSTM. This is not true for the decoder because as each step we want to choose if we are going to use teacher forcing or not. If we always wanted to use teacher forcing, i.e. `teacher_forcing_ratio = 1.0` and always use the ground truth as the input for each time-step whilst decoding, then we could discard the explicit `for` loop. However, using a teacher forcing ratio of less than 1 is desired so our model can learn to handle the case where it makes decoding mistakes.
