### ISSUE TITLE
Adding layers to the encoder and decoder of seq2seq

### ISSUE THREAD

**Issue by dopu2k16** [bentrevett/pytorch-seq2seq#154]
Hi, 
Can you point out the change in dimension for the forward() for encoder if we add number of layers in your tutorial instead of using single layer of GRU layers? May you update the source code for encoder and decoder of n layers of GRU?

**Comment by maqboolkhan** [comment]
I have the same question, It will be really helpful as I am struggling with hidden_state output with `num_layers=2`.
