### ISSUE TITLE
Tutorial 4: RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

### ISSUE THREAD

**Issue by Sturzgefahr** [bentrevett/pytorch-seq2seq#156]
I'm getting errors on both my local machine (torch 1.7.1) and Colab instance (torch 1.7.0+cu101) when trying to train the model in Tutorial 4:

```{python}
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-66-56e44b8b2212> in <module>()
      8     start_time = time.time()
      9 
---> 10     train_loss = train(model, train_iterator, optimizer, criterion, CLIP)
     11     valid_loss = evaluate(model, valid_iterator, criterion)
     12 

5 frames

/usr/local/lib/python3.6/dist-packages/torch/nn/utils/rnn.py in pack_padded_sequence(input, lengths, batch_first, enforce_sorted)
    242 
    243     data, batch_sizes = \
--> 244         _VF._pack_padded_sequence(input, lengths, batch_first)
    245     return _packed_sequence_init(data, batch_sizes, sorted_indices, None)
    246 

RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

I traced the error back to `pack_embedded` in the `Encoder.forward` definition.  It appears that in newer PyTorch builds, `nn.utils.rnn.pack_padded_sequence` can't handle CUDA tensors.  This appears to be a known issue (cf. https://github.com/pytorch/pytorch/issues/43227), and the recommended solution there is to move the second parameter in `pack_padded_sequence` to the cpu.

I can confirm that the following changes will work

```{python}
class Encoder(nn.Module):
    def __init__(self, input_dim, emb_dim, enc_hid_dim, dec_hid_dim, dropout):
        super().__init__()

        self.embedding = nn.Embedding(input_dim, emb_dim)

        self.rnn = nn.GRU(emb_dim, enc_hid_dim, bidirectional=True)

        self.fc = nn.Linear(enc_hid_dim * 2, dec_hid_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, src, src_len):

        embedded = self.dropout(self.embedding(src))

        # added .cpu() cf.: https://github.com/pytorch/pytorch/issues/43227
        packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded,
                                                            src_len.cpu())

        packed_outputs, hidden = self.rnn(packed_embedded)

        outputs, _ = nn.utils.rnn.pad_packed_sequence(packed_outputs)

        hidden = torch.tanh(self.fc(torch.cat((hidden[-2,:,:],
                                               hidden[-1,:,:]), dim=1)))

        return outputs, hidden
``` 
but I suspect that moving tensors to the cpu slows down training.

P.S. Big fan of these tutorials.  Thanks for putting these together!

**Comment by bentrevett** [comment]
Cheers for pointing this out. Haven't yet run the tutorials with the latest PyTorch so hadn't spotted these. Will do a fix now.

**Comment by suvasis** [comment]
any fix for this issue?

**Comment by bentrevett** [comment]
@suvasis This should be fixed in the latest versions of notebook 4. Please let me know if not. The only change needed was changing:

`packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, src_len)`

to:

`packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, src_len.cpu())`

or:

`packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, src_len.to('cpu'))`
