### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by EthanChen911238** [bentrevett/pytorch-seq2seq#16]
Hi, i implement Packed Padded Sequences, Masking and interface, but I got some problem with cuda out of memory. My own dataset has about 50000 sentences and I already lower batch size to 1, but I still got RuntimeError with out of memory. Would you provide some solutions for me, thanks

**Comment by EthanChen911238** [comment]
Here is my model setting
![image](https://user-images.githubusercontent.com/40733301/56460317-91fc6f80-63d3-11e9-9723-e4ac64c35b10.png)
GPU : GeFprce GTX 1080 Ti 11G

**Comment by xelibrion** [comment]
It is a fairly large model, try to restrict vocabulary to some reasonable size. Alternatively, you can experiment with reducing size of either embedding layers or hidden layers of your encoder/decoder.

**Comment by bentrevett** [comment]
I'll basically echo what @xelibrion has said.

I have the same GPU as you (1080 Ti) and it's at 50% capacity with only 20mil parameters (vocab size of ~9k). You'll have to either reduce the amount of parameters in your model as @xelibrion has suggested or try on another GPU with larger capacity.
