### ISSUE TITLE
Suggest ask the users (whoever is using this tutorial) to update their spaCy to 3.0 as 2.0 is suddenly very slow today

### ISSUE THREAD

**Issue by cestwc** [bentrevett/pytorch-seq2seq#165]
I have adapted the tutorial code to run some other tasks, and found that all my codes are stuck at 'train_data, test_data = data.TabularDataset.splits' step. I've tried the suggestion as in this [issue](https://github.com/bentrevett/pytorch-sentiment-analysis/issues/6).

Indeed, using ```some_text'.split(' ')``` actually makes that step way much faster.

Then I tried the 4th tutorial one more time, and it is also very slow.

So I updated my spaCy package to 3.0, and the speed becomes normal again.

**Comment by benceOlahEdu** [comment]
I experienced the same.

**Comment by bentrevett** [comment]
spaCy is doing a lot more than just tokenization under the hood so it's inevitable it will take longer than simply splitting on spaces.

The README does mention spaCy 3.0, so hopefully people should upgrade. I might make a note of it in the tutorials. Do you have any idea of how much faster 3.0 is than 2.0?

**Comment by cestwc** [comment]
spaCy 2.0 used to be not that slow. Now, for the task that take spaCy 2.0 1.5h (not even finished), spaCy 3.0 uses 4 mins.
