### ISSUE TITLE
Could you provide functions to convert the network outputs into sentences?

### ISSUE THREAD

**Issue by wfchen-umich** [bentrevett/pytorch-seq2seq#17]
Hi, thanks for the great repo. I am confused about how to convert the network outputs into sentence. Could you provide one? Thanks a lot!

**Comment by PonteIneptique** [comment]
Sorry to come in on a repo that is not mine but actually chapter 4 contains it :) https://github.com/bentrevett/pytorch-seq2seq/blob/master/4%20-%20Packed%20Padded%20Sequences%2C%20Masking%20and%20Inference.ipynb 
I built my own until I actually found this one.

**Comment by wfchen-umich** [comment]
I see, thanks! @PonteIneptique
