### ISSUE TITLE
using CTC loss instead of Cross Entropy loss:

### ISSUE THREAD

**Issue by kerolos** [bentrevett/pytorch-seq2seq#177]
In all Tutorials, the cross entropy has been used. 
i would like to change this loss function to be CTC (i am using those model for g2p purpose not for translation). 
is there any hints or idea, how can I change that parameters and write a proper code for this tutorial (https://github.com/bentrevett/pytorch-seq2seq/blob/master/3%20-%20Neural%20Machine%20Translation%20by%20Jointly%20Learning%20to%20Align%20and%20Translate.ipynb ), i would really appreciate your advice.

**For criterion = nn.CrossEntropyLoss(ignore_index = TRG_PAD_IDX) :** 

        src = batch.src
        trg = batch.trg
        optimizer.zero_grad()
        output = model(src, trg)
        #trg = [trg len, batch size]
        #output = [trg len, batch size, output dim]
        output_dim = output.shape[-1]
        output = output[1:].view(-1, output_dim)
        trg = trg[1:].view(-1)
        #trg = [(trg len - 1) * batch size]
        #output = [(trg len - 1) * batch size, output dim]
        loss = criterion(output, trg)

**For criterion =  nn.CTCLoss(blank=(output_dim-1) , zero_infinity=True) :** 

        src = batch.grapheme
        trg = batch.phoneme
        optimizer.zero_grad()
        output = model(src, trg)
        #output = [trg len, batch size, output dim]
         output_softmax=F.log_softmax(output )
        input_length = torch.full(size=(TrainConfig.batch_size_jointly,), fill_value=len(src), dtype=torch.long)
        target_length = torch.full(size=(TrainConfig.batch_size_jointly,), fill_value= len(trg), dtype=torch.long)
        loss = criterion(output_softmax,   trg.view(-1)  ,input_length, target_length)

The CTCLoss method should take the following parameters:
1-output_softmax should be:  (T: Input sequence length or number of timesteps ,N: Batch size  ,C: Number of classes(including blank)) this is the output from the log_softmax.
2- targets - a tensor which contains the expected sequence of "graphemes or translated language"
3-input_lengths - the length of the input sequence after it is processed by the convolutional layers (i.e. post-convolution width)
4-target_lengths - the length of the target sequence.
for more details, please look at this explanation (https://discuss.pytorch.org/t/ctcloss-with-warp-ctc-help/8788/3)

-In my case: 
The model 
Seq2Seq(
  (encoder): Encoder(
    (embedding): Embedding(44, 256)
    (rnn): GRU(256, 512, bidirectional=True)
    (fc): Linear(in_features=1024, out_features=512, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
  (decoder): Decoder(
    (attention): Attention(
      (attn): Linear(in_features=1536, out_features=512, bias=True)
      (v): Linear(in_features=512, out_features=1, bias=False)
    )
    (embedding): Embedding(43, 256)
    (rnn): GRU(1280, 512)
    (fc_out): Linear(in_features=1792, out_features=43, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
) 
       1-# output_softmax .size() : torch.Size ([13, 64, 43]) #something went wrong because it should be with this dimension ([15,64,43])
        2-# targets.size() : torch.Size([768])   # "sum of all target value length (sum of all target_lengths), it should be 13 X 64"
        3- # input_lengths : tensor tensor([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) # "length of each input sequence with pad X Batch size "
        4-# target_lengths : tensor([13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13]) # "length of each target sequence without pad X Batch size "
        
**_My question how can i adapt the first input to be in the right format._** 
 RuntimeError: Expected input_lengths to have value at most 13, but got value 15 (while checking arguments for ctc_loss_cpu)

**Comment by Andrew-Xu1** [comment]
Hey friend ! Have you solved this problem？Now, I also meet this question.
