### ISSUE TITLE
why this

### ISSUE THREAD

**Issue by zhiqiangohuo** [bentrevett/pytorch-seq2seq#178]
In your transformer block 50    

If  input parameters is 

> translate_sentence(src, SRC, TRG, model, device)
 will get this result 

> predicted trg = ['.', 'einer', 'mann', '.', 'bei', 'jagt', 'ihre', 'kind', '.', 'benutzen', 'ein', '<eos>']

if replace TRG with SRC
>translate_sentence(src, SRC, SRC, model, device)
will get this result  (I only train 1 epoch)
> predicted trg = ['a', 'brown', 'dog', 'running', 'after', 'the', 'black', 'dog', '.', '<eos>']

i guess if decoder have mistake in your code?

**Comment by bot66** [comment]
Yes it is, because the model trained with wrong target.
check this issue:
https://github.com/bentrevett/pytorch-seq2seq/issues/182
