### ISSUE TITLE
spacy load not loading

### ISSUE THREAD

**Issue by neqkir** [bentrevett/pytorch-seq2seq#179]
Had to add 

```
import spacy.cli 
spacy.cli.download("de_core_news_sm")
```

else it would not load `de_core_news_sm`

See https://stackoverflow.com/questions/62822737/oserror-e050-cant-find-model-de-it-doesnt-seem-to-be-a-shortcut-link-a

**Comment by bentrevett** [comment]
Did you make sure to run the commands for downloading the models first?

```
python -m spacy download en_core_web_sm
python -m spacy download de_core_news_sm
```

This is listed in the README and in the first section of the first notebook.
