### ISSUE TITLE
How to do a single prediction?

### ISSUE THREAD

**Issue by Jeblii** [bentrevett/pytorch-seq2seq#18]
Hey, I am new to using deep learning frameworks. Does anyone know how to use the model (for example from the 1st notebook) to do a single prediction?

**Comment by bentrevett** [comment]
The 4th notebook shows how to use the seq2seq model for inference. Let me know if any part needs clarifying.

**Comment by Jeblii** [comment]
Hi, managed to get it working. Thanks a lot :)
