### ISSUE TITLE
Multi-gpu might fail with Attention is all you need

### ISSUE THREAD

**Issue by Aaron-Zhao123** [bentrevett/pytorch-seq2seq#180]
Running Attention is All you Need might fail if one naively uses multiple GPUs might trigger
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!`

I think this is simply beccause how scales are defined, eg:
` self.scale = torch.sqrt(torch.FloatTensor([self.head_dim])).to(device)`

A simple solution to this might be just define them as float values:
`import math; self.scale = math.sqrt(hid_dim)`

**Comment by asigalov61** [comment]
@Aaron-Zhao123 You probably did not set up the "device" properly. It works great on my end if I set "device" to "cuda" (not "cuda:0" or "cuda:1". And then adding model = nn.DataParallel(a model after the model creation code.

Your solution would simply default to the default device which may still cause problems IMHO.

Hope this helps.

**Comment by Aaron-Zhao123** [comment]
@asigalov61 I am not sure I understood what you meant here. My solution is to put `self.scale` as a simple `float` ...  so it does not ping down to any devices. 

`DataParallel` works by first pinging down all torch modules to cuda:0 and then perform a scatter gather on N gpus, putting `self.scale = torch.FloatTensor ...` is dangerous and it is recommended to use `self.scale = nn.Parameter ...`. However, since `scales` is not even a trainable parameter here, putting it as a normal `float` is more convinient.

**Comment by bentrevett** [comment]
@Aaron-Zhao123 Thanks for pointing this out. I'll be sure to change it. I feel like I remember trying to have `scale` as a normal float, and it was not working for some reason, but it's been so long ago that I can't fully remember.

I am planning to update the notebooks soon, so I will make this change. Alternatively, if you make a pull request I will gladly accept it.
