### ISSUE TITLE
Why using tanh function

### ISSUE THREAD

**Issue by karimmahalian** [bentrevett/pytorch-seq2seq#194]
Hi,

Thank u for this great repo. Could u plz tell me why using tanh (instead of other activation function) in this repo
https://github.com/bentrevett/pytorch-seq2seq/blob/master/3%20-%20Neural%20Machine%20Translation%20by%20Jointly%20Learning%20to%20Align%20and%20Translate.ipynb

![Screen Shot 2023-01-11 at 8 03 04 AM](https://user-images.githubusercontent.com/90440701/211739529-3ea8a195-a455-4ba8-8e21-5d46e2f43f66.png)

Many thanks in advance

**Comment by Anirudh257** [comment]
tanh function is helpful in preventing the exploding gradients in seq2seq tasks. But you can try other activation functions like ReLU as well here.

**Comment by karimmahalian** [comment]
Many thanks for answering my question. Did you try the ReLU function? If yes did it give better or worst results than tanh?

Thank u

**Comment by Anirudh257** [comment]
Hi, I haven't tried ReLU in this context but have tried it for other projects. Yes, ReLU gave better results.
