### ISSUE TITLE
no module named 'torchtext.legacy'

### ISSUE THREAD

**Issue by Hzzhang-nlp** [bentrevett/pytorch-seq2seq#198]
My Python version is 3.8 and Pytorch version is 2.0, but an error is reported

**Comment by Jiazxu** [comment]
Torchtext >= 0.12 had removed Field and lagacy modules. 
You can try [THIS](https://github.com/pytorch/text/blob/master/examples/legacy_tutorial/migration_tutorial.ipynb) :
`from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pad_sequence

from collections import Counter
from torchtext.datasets import Multi30k
from torchtext.vocab import vocab
from torchtext.data import get_tokenizer`

**Comment by AnLittleHong** [comment]
The torch version is too high. Torchtext version is available at 0.9.0
