### ISSUE TITLE
No way to generate output from models

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [bentrevett/pytorch-seq2seq#20]
The code of Seq2Seq models is dependent on the presence of target, and would not function when the target argument to Seq2Seq.forward is supplied as None. This makes code unsuitable for the usage in inference.

Code could be modified to work without target, but that requires modifying Seq2Seq code and providing additional arguments, as max target sequence length and , SOS character, ...

But without modification, it would be simply impossible to use the code for producing actual output when applying seq2seq models

**Comment by bentrevett** [comment]
Notebook 4 shows how to appropriately modify the `seq2seq` model for inference. I have decided to only show this for the attention based model as the ones before it give pretty poor translations. I will add inference to the conv. seq2seq and the transformer models when I (eventually) get around to finishing them.
