### ISSUE TITLE
tutorial 1, equations for decoder

### ISSUE THREAD

**Issue by antgr** [bentrevett/pytorch-seq2seq#26]
Thank you very much for this epic notebook. It helped me understand a lot of thinks, and this is in progress. I have a question.
The equations for decoder are:
$$\begin{align*}
(s_t^1, c_t^1) = \text{DecoderLSTM}^1(y_t, (s_{t-1}^1, c_{t-1}^1))\\
(s_t^2, c_t^2) = \text{DecoderLSTM}^2(s_t^1, (s_{t-1}^2, c_{t-1}^2))
\end{align*}$$
but,  we say later on that: " This produces an `output` (hidden state from the top layer of the RNN), a new `hidden` state (**one for each layer, stacked on top of each other**) and a new `cell` state (also **one per layer, stacked on top of each other**)"
So, for the decoder of the second layer, I would expect to have also the c_t^1  as its input:
 s_t^1, c_t^1, (s_{t-1}^2, c_{t-1}^2

**Comment by bentrevett** [comment]
Not sure I understand your question, but the cell states do not pass upwards between layers, c_t^1 will not be input into the second layer of the decoder. 

We get a hidden and cell state per layer, which are h_t^L and c_t^L (where L is the layer number superscript).

**Comment by antgr** [comment]
OK, but what confuses me is in the phrase "**and a new cell state (also one per layer, stacked on top of each other)**". My question is: How can we stack on top of each other the two cell states, if we do not pass the cell state of layer one to layer two as input?

**Comment by bentrevett** [comment]
Ah, I get your question now.

You can think of the hidden states and cell states as being returned by a function. This function (the LSTM) returns L hidden states and L cell states -  where L is the number of layers. These L states are stacked on top of each other, so you don't get L tensors, you just get 1. 

This stacking of states does not depend on how they are calculated.

**Comment by bentrevett** [comment]
Hopefully this might clarify things, a simple LSTM implementation in PyTorch:

```py
import torch
import torch.nn as nn
import torch.nn.functional as F

class LSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()

        #weights for input connections
        self.w_f = nn.Parameter(torch.randn(input_dim, hidden_dim))
        self.w_i = nn.Parameter(torch.randn(input_dim, hidden_dim))
        self.w_o = nn.Parameter(torch.randn(input_dim, hidden_dim))
        self.w_c = nn.Parameter(torch.randn(input_dim, hidden_dim))

        #weights for recurrent connections
        self.u_f = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
        self.u_i = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
        self.u_o = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
        self.u_c = nn.Parameter(torch.randn(hidden_dim, hidden_dim))

    def forward(self, x, h, c):

        f = torch.sigmoid(x @ self.w_f + h @ self.u_f)
        i = torch.sigmoid(x @ self.w_i + h @ self.u_i)
        o = torch.sigmoid(x @ self.w_o + h @ self.u_o)
        c = f * c + i * torch.sigmoid(x @ self.w_c + h @ self.u_c)
        h = o * torch.tanh(c)

        return h, c

input_dim = 128
hidden_dim = 256

#input tensor, e.g. word after going through embedding layer
x = torch.randn(input_dim) 

#initial hidden and cell state for first layer
h_1 = torch.randn(hidden_dim)
c_1 = torch.randn(hidden_dim)

#initial hidden and cell state for second layer
h_2 = torch.randn(hidden_dim)
c_2 = torch.randn(hidden_dim)

#initialize lstms for each layer
first_layer_lstm = LSTM(input_dim, hidden_dim)
second_layer_lstm = LSTM(hidden_dim, hidden_dim)

#input, x, used as input for first layer
h_1, c_1 = first_layer_lstm(x, h_1, c_1)

#hidden state from first layer, h_1, used as input for second layer
h_2, c_2 = second_layer_lstm(h_1, h_2, c_2)
```

Instead of implementing the LSTM with multiple layers, I've implemented each layer as an individual LSTM. In PyTorch you only need to specify a single LSTM with the number of layers, but it basically does the same as above, with the two LSTMs wrapped up into one LSTM class. 

As you can see, we get two cell states, `c_1` and `c_2`, one for each layer, but the cell state from the first layer does not pass to the second layer - whereas the hidden state output from the first layer does pass to the second layer. 

In PyTorch, `c_1` and `c_2` are then stacked on top of each other to form a single tensor. Thus, we get "one per layer, stacked on top of each other". 

Let me know if this helped at all or needs more clarifying!

**Comment by antgr** [comment]
Thank you very much!!
