### ISSUE TITLE
forward function in encoder

### ISSUE THREAD

**Issue by Han8931** [bentrevett/pytorch-seq2seq#3]
Thank you for your nice tutorial.

I just have one question.

As I understand encoder should take input and previous hidden state, but your encoder only takes input data.

could you explain it?

**Comment by bentrevett** [comment]
The way PyTorch RNNs work is that if you feed them a sequence of words (that have been embedded), they will handle the recurrent feeding of the hidden state for you. This is done by:

``` python
outputs, (hidden, cell) = self.rnn(embedded)
```

Why do we only feed an input and not an initial hidden state (and cell state in an LSTM) here? If you check the PyTorch documentation for the LSTM (https://pytorch.org/docs/stable/nn.html#torch.nn.LSTM) you can see:

``` markdown
If *(h_0, c_0)* is not provided, both **h_0** and **c_0** default to zero.
```

Thus, by not passing a hidden (and cell) state to the `self.rnn`, we are effectively passing an initial hidden state, h_0, (and initial cell state, c_0) as a tensor of all zeros. 

I will add a few words about it in the tutorial soon.

Hopefully this answers your question.

**Comment by bentrevett** [comment]
Added this to the **Encoder** section in the first notebook:

"You may notice that we do not pass an initial hidden and cell states to the RNN. This is because, as noted in the documentation [links to the PyTorch LSTM documentation], that if no hidden/cell state is passed to the RNN, it will automatically create an initial hidden/cell state as a tensor of all zeros."

Hopefully this clears up any confusion in the future.

**Comment by vgoklani** [comment]
Thanks for the update. It would be interesting to see other types of initial hidden states, aside from the zero state, that could potentially lead to more efficient learning. After all, there must be a reason why one can manually pass the hidden state.

**Comment by bentrevett** [comment]
Yes, you can actually *learn* an initial state by defining it as a `nn.Parameter`. I don't believe any of the papers I'm going to implement in this series of notebooks do that though, but I may create an "appendix" notebook where I mention a few things not discussed in the papers.

**Comment by Han8931** [comment]
Thank you for your nice answer.

However, I was not just talking about the initial hidden state.

The documentation for the LSTM (https://pytorch.org/docs/stable/nn.html#torch.nn.LSTM) unit takes two inputs, input data, and a tuple of hidden state and cell state. 

When I study with this tutorial (https://github.com/spro/practical-pytorch/blob/master/seq2seq-translation/seq2seq-translation.ipynb), they also implement their encoder like below:

````PyThon3
class EncoderRNN(nn.Module):
    def __init__(self, input_size, hidden_size, n_layers=1):
        super(EncoderRNN, self).__init__()
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.n_layers = n_layers
        
        self.embedding = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size, n_layers)
        
    def forward(self, word_inputs, hidden):
        # Note: we run this all at once (over the whole input sequence)
        seq_len = len(word_inputs)
        embedded = self.embedding(word_inputs).view(seq_len, 1, -1)
        output, hidden = self.gru(embedded, hidden)
        return output, hidden

    def init_hidden(self):
        hidden = Variable(torch.zeros(self.n_layers, 1, self.hidden_size))
        if USE_CUDA: hidden = hidden.cuda()
        return hidden````

As you see, self.gru in forward function takes previous hidden states.

**Comment by bentrevett** [comment]
Sorry for misunderstanding.

In PyTorch, when you feed a sequence into an LSTM it will automatically calculates the hidden state for each timestep, and uses that hidden state as input it for the next token in the sequence. This is all done for you. You do not manually need to feed in one word at a time, repeatedly getting the new hidden state and recurrently feeding it back into the LSTM (which the linked tutorial is doing). That tutorial is doing the same thing we are, but in an incredibly inefficient way. 

This model uses an RNN without loops over each word individually:
- https://github.com/pytorch/examples/blob/master/snli/model.py#L34

So does the one in this tutorial:
- https://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html#implementation-notes

If you edit the code in these tutorials to manually loop over the words, you should get very similar results, however things will be a bit slower.

**Comment by Han8931** [comment]
I really appreciate your clear answer.
Now I understand it! 
Thank you for this great tutorial!

**Comment by Han8931** [comment]
Thank you for your great answer!

However, as I understand your explanation, I think the decoder also needs not to get the hidden state right? 

````PyThon3
class Decoder(nn.Module):
.
.
.
def forward(self, input, hidden, cell):
        
        #input = [batch size]
        #hidden = [n layers * n directions, batch size, hid dim]
        #cell = [n layers * n directions, batch size, hid dim]
        
        #n directions in the decoder will both always be 1, therefore:
        #hidden = [n layers, batch size, hid dim]
        #context = [n layers, batch size, hid dim]
        
        input = input.unsqueeze(0)
        
        #input = [1, batch size]
        
        embedded = self.dropout(self.embedding(input))
        
        #embedded = [1, batch size, emb dim]
                
        output, (hidden, cell) = self.rnn(embedded, (hidden, cell))
.
.
.
````

**Comment by bentrevett** [comment]
The decoder is different because you aren't starting from "nothing". You want to start it from an initial hidden state that is an encoded representation of your input sentence.

If you don't pass an initial hidden state to the decoder, it won't know anything about the sentence you are trying to translate as it hasn't "seen" it. The initial hidden state to the decoder - which is the final hidden state of your encoder - represents your entire input sentence and your decoder needs to "see" it so it has some idea of what it is trying to decode.

**Comment by Han8931** [comment]
Thank you for your gentle and nice tutorials!

I hope to see your next tutorial about "attention" soon.

**Comment by bentrevett** [comment]
Thanks guys. Hopefully will get it finished by the end of this weekend.
