### ISSUE TITLE
Attention mechanism

### ISSUE THREAD

**Issue by antgr** [bentrevett/pytorch-seq2seq#31]
I see that there are many types of attention, for example from Allennlp library, we can import:
`LinearAttention, CosineAttention, BilinearAttention, DotProductAttention, BahdanauAttention`.
What type of attention do you use in the examples? I maybe can find out studying each of the above and compare with the attention implementations in the examples, but I think it could help me if you could provide some information of your choices. Thanks a lot.

**Comment by bentrevett** [comment]
I had a quick look at the AllenNLP library and couldn't see a `BahdanauAttention`, however the `LinearAttention` with the default `combination` argument - found [here](https://github.com/allenai/allennlp/blob/master/allennlp/modules/attention/linear_attention.py) - is the same attention implementation as these notebooks.

**Comment by antgr** [comment]
Thanks! (Yes you are right about BahdanauAttention).
