### ISSUE TITLE
Multi Layer Decoder

### ISSUE THREAD

**Issue by sheoranhimansh** [bentrevett/pytorch-seq2seq#37]
Hi,
Really good tutorial!
I had one doubt though, can you please explain how would you construct a multi layer decoder instead of a single layer. How would you pass the initial hidden state and how would you incorporate attention in all the layers of the decoder?

Thank You

**Comment by kuldeep7688** [comment]
According to me, 
Initial hidden states will be passed as mentioned below:
- pass the concatenated back and forward hidden of each layer through a linear layer
- the linear layer will learn how to best merge the hidden states of the bidirectional rnn.
- Suppose we have two layers in encoder so we will have one merged output for each layer of the encoder

- If you have a single layer in encoder 
       - pass the merged outputs from another linear layer and then pass this as the initial hidden layer for decoder
- If you have two layers in the decoder 
       - pass the merged outputs respectively as the initial hidden states of the decoder
- if you have more than two layers in the decoder
       - concatenate the merged outputs and pass them through the linear layer and then use view to the respective hidden state for each layer of the decoder.

And for attention I think in rnn encoder-decoder you do not provide attention to the every layer.
Suppose you have a decoder of two layer then you will concatenate attention (with encoder outputs) with embedded and pass to the rnn's first layer. And you will again concatenate attention (with encoder outputs) with the outputs of the last layer of decoder and pass them to the linear layer to predict the token.

Would love to discuss whether I am thinking in the right direction or not.

**Comment by bentrevett** [comment]
@kuldeep7688 is correct on all counts. 

For the multi-layer decoder part it all depends on how many layers your encoder and decoders both have - there isn't an agreed upon "correct" way to do it. The methods @kuldeep7688 mentioned are the most common that I've seen.

As for attention in multi-layer decoder, doing all of the attention operations is time consuming so I would be hesitant to apply attention to every layer and just stick to calculating it how @kuldeep7688 says.
