### ISSUE TITLE
Why don't we use `RNNCell` instead of `RNN`?

### ISSUE THREAD

**Issue by standbyme** [bentrevett/pytorch-seq2seq#40]
https://github.com/bentrevett/pytorch-seq2seq/blob/541bdb064d3264fcf477594165d2c6a0eee2f631/1%20-%20Sequence%20to%20Sequence%20Learning%20with%20Neural%20Networks.ipynb#L490

If we use `RNNCell`, this `unsqueeze` can be removed.

**Comment by bentrevett** [comment]
Yes, that is true. The main reason I didn't use the `RNNCell` is because I didn't know about it when first creating these tutorials. I don't think I will change it though as I don't really want to get into explaining the different between `RNN` and `RNNCell` in the tutorials and I think the "we unsqueeze because we need to add a sequence length of 1" explanation is sufficient.

Let me know if you disagree.

**Comment by standbyme** [comment]
Thanks for your tutorial and reply.

I don't agree with you. `RNN` is currently used in all major documents(such as [PyTorch: NLP FROM SCRATCH: TRANSLATION WITH A SEQUENCE TO SEQUENCE NETWORK AND ATTENTION](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html)), and these documents make me very confused about `Decoder`'s unfolding structure.

The key to the `Decoder`'s technology is to pass the output of the previous step to the next step. As a beginner of Seq2Seq, I haven’t understood this well for a long time because of the existence of `RNN`, which gives me the illusion that the input of each time step is a **sequence** instead of a **word**.

**Comment by bentrevett** [comment]
I agree, it is confusing at first. I'll make sure I'm more explicit that the input for the decoder at each time-step is a single token and not a sequence. 

In the mean time, I'll think about changing it to an `RNNCell`.

**Comment by bentrevett** [comment]
One downside I've just come across with regards to using the `LSTMCell` is that if you are using multiple layers you will need multiple `LSTMCells`, which the normal `LSTM` model handles for us.

**Comment by standbyme** [comment]
Thanks.

I think the primary task of this document is to help beginners quickly understand the basic structure of `Seq2Seq` which will help them build their own `Stacked RNN`. 😃
