### ISSUE TITLE
Convolutional Seq2Seq

### ISSUE THREAD

**Issue by kuldeep7688** [bentrevett/pytorch-seq2seq#41]
In attention calculating step in decoder:
```
#attention = [batch size, trg sent len, src sent len]
attended_encoding = torch.matmul(attention, (encoder_conved + encoder_combined))
#attended_encoding = [batch size, trg sent len, emd dim]
```

I think it should be 

`attended_encoding = torch.matmul(attention, encoder_combined)`

encoder_combined has the embedded(of encoder) plus the conved (encoder's last layers output)
as mentioned in the paper.

> The conditional inputclito the current decoder layer is a weighted sum of the encoder outputs as well as the input element embeddings ej.

Also in decoder step, we should do the residual connection before applying attention according to my understanding of the figure given in the paper. But in your code you make your residual connection after applying attention.

Please help me understand if I am missing something.

**Comment by bentrevett** [comment]
I'll look more closely at the potential attention error.

I believe in the decoder we apply to residual connection after the attention. If we check the official(?) repository, we first calculate the attention (https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L463) and then apply the residual connection (https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L476). 

That lines up with how I see the image, as the attention (circled in red) should happen before the residual connection (circled in green).

![](https://i.imgur.com/P9Vls15.png).

**Comment by bentrevett** [comment]
The attention thing was an error. Going to push an update later today. Cheers for spotting it!
