### ISSUE TITLE
found a small typo

### ISSUE THREAD

**Issue by Huffon** [bentrevett/pytorch-seq2seq#42]
Hi, bentrevett. 
I really love your tutorial. Nowadays, I literally scrutinize your tutorial to improve my NLP knowledge 👍 

BTW, In tutorial 3 - Neural Machine Translation by Jointly Learning to Align and Translate, Seq2Seq section , I think there is a small typo.

_This seq2seq encapsulator is similar to the last two. The only difference is that the encoder returns both the final hidden state (which is the final hidden state from both the forward and backward encoder RNNs passed through a linear layer) to be used as the initial hidden state for the **encoder,**_ 

I think the word "encoder" should be replaced by **decoder**, since the final hidden state of the encoder used to initialize the decoder ! And also _Briefly going over all of the decoding steps:_ is a redundancy, cause the next sentence is also _Briefly going over all of the steps:_

Thanks for sharing your tutorial again.

**Comment by bentrevett** [comment]
Thanks for the kind words and for spotting the errors. Have just pushed a fix - let me know if you spot any more (I'm sure there will be some hiding somewhere).
