### ISSUE TITLE
Do we have to append <sos> and <eos> token to source sentence?

### ISSUE THREAD

**Issue by Huffon** [bentrevett/pytorch-seq2seq#43]
Hi, Ben Trevett
Now I'm training seq2seq with attention model based on your code

And I got curious, do  we really need `<sos>` and `<eos>` tokens for our source sentence?
For target sentence, they absolutely are needed.

But I think, for source sentence, they are just useless tokens which prevent model from learning input tokens well.
I want to hear your opinion !

Thanks in advance

**Comment by bentrevett** [comment]
@Huffon Sorry for taking so long to get back to this. I did run the experiments without the `<eos>` and `<sos>` tokens in the source sentence and they seemed to have no effect on the result. 

Notebook 4 has us viewing the attention during inference, and the model never pays even the slightest attention to the `<sos>` and `<eos>` tokens there.

Hopefully this is enough to show that the model simply learns to ignore them.
