### ISSUE TITLE
About seq2seq tutorial 2

### ISSUE THREAD

**Issue by deartonym** [bentrevett/pytorch-seq2seq#44]
In the forward part of Class of Seq2Seq, why the encoder part does not have loop?

To my understanding, the encoder cell should take in an initial hidden state (usually all zeros), and the first input, and output the new hidden state to for the next word to be encoded. It should be like a loop with encoding length, if not included the End of Sequence token.

Thanks.

**Comment by bentrevett** [comment]
In PyTorch, if you feed a sequence to an RNN it will recurrently feed each item of the sequence in for you - there is no need for a loop. In the encoder, as we already have the entire input sequence (the source sentence) available we just need to feed it to the RNN and PyTorch handles the recurrent feeding of the subsequent items in the sequence.

In the decoder, we also have the full sequence available, the target sentence, but we don't want to just feed in the actual next tokens recurrently into the model - we also want to sometimes feed in the next token predicted by the model.  As we are sometimes using the predictions of the model, we have to do a loop and make a decision on each loop iteration what we are going to use as the next input to the decoder (the actual next token or the predicted next token).

**Comment by deartonym** [comment]
> In PyTorch, if you feed a sequence to an RNN it will recurrently feed each item of the sequence in for you - there is no need for a loop. In the encoder, as we already have the entire input sequence (the source sentence) available we just need to feed it to the RNN and PyTorch handles the recurrent feeding of the subsequent items in the sequence.
> 
> In the decoder, we also have the full sequence available, the target sentence, but we don't want to just feed in the actual next tokens recurrently into the model - we also want to sometimes feed in the next token predicted by the model. As we are sometimes using the predictions of the model, we have to do a loop and make a decision on each loop iteration what we are going to use as the next input to the decoder (the actual next token or the predicted next token).
> 
> Let me know if that clarifies things.

Yeah thanks! I tried it and yes if the input is a full sequence, the LSTM will iteratively do the auto feeding and broadcasting the hidden states.

Thanks buddy!
