### ISSUE TITLE
Inference in transformer seq2seq (ex. 6)

### ISSUE THREAD

**Issue by gorka96** [bentrevett/pytorch-seq2seq#48]
Hi!

I was working on the code of the last tutorial (the transformer), and I have some doubts about how to do the inference correctly. 

```
def translate_sentence(model, tokenized_sentence):
    model.eval()
    tokenized_sentence = ['<sos>'] + [t for t in tokenized_sentence] + ['<eos>']
    numericalized = [SRC.vocab.stoi[t] for t in tokenized_sentence] 
    tensor = torch.LongTensor(numericalized).unsqueeze(1).to(device) 
    translation_tensor_logits = model(tensor, None) 
    translation_tensor = torch.argmax(translation_tensor_logits.squeeze(1), 1)
    translation = [TRG.vocab.itos[t] for t in translation_tensor]
    translation, attention = translation[1:], attention[1:]
    return translation
```

I guess that is something like this, but it gives an error in the call to 
 `model(tensor, None)`, 
as it expects a target tensor as the second parameter. 

using the src tensor twice:  
`model(tensor, tensor)`
returns an answer, in the correct format, but I'am not sure about it and it doesn't look very good (but that will be probably because I trained for 2 epochs and used small numbers for hiperparameters).  

Can anyone help with this? thanks

**Comment by hawkeoni** [comment]
Hello, @gorka96.
https://github.com/bentrevett/pytorch-seq2seq/pull/49
In this pull request you can see function in Seq2Seq class which does the inference.

**Comment by gorka96** [comment]
Thanks @hawkeoni !
