### ISSUE TITLE
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

### ISSUE THREAD

**Issue by banunitte** [bentrevett/pytorch-seq2seq#54]
getting run time time error for stacked decoder layer.(decoder with 2 gru layer)

![image](https://user-images.githubusercontent.com/6847024/68532165-329a8880-0340-11ea-8302-b36d9f360dfd.png)

**Comment by bentrevett** [comment]
Just setting `num_layers` in the decoder to 2 is not enough. 

Your code is decoding the very first token fine, but during that detokenization the `hidden` returned by the GRU will be `[2, batch size, dec hid dim]` which will not be changed by the `hidden.squeeze(0)`. Thus when it is fed to the `attention` module on the second decoding step `hidden` will have 3-dimensions and not 2. Thus the `unsqueeze` shown at the bottom of your screenshot adds a fourth dimension which does not match up with the `.repeat` only having 3 arguments.

**Comment by Mounika2405** [comment]
Hi,

I'm facing the same issue. Could you please help me resolve this issue?

**Comment by abhishekchandak** [comment]
> Hi,
> 
> I'm facing the same issue. Could you please help me resolve this issue?

Did you solve this issue? I can't figure it out
