### ISSUE TITLE
Just want to say a big thank you!

### ISSUE THREAD

**Issue by Hans0124SG** [bentrevett/pytorch-seq2seq#59]
This tutorial is really amazing for people who want to get started with NLP and seq2seq models in pytorch with torchtext. Clear structure and very detailed documentation on the dimensions of the tensors. Thanks a lot for your effort.

**Comment by bentrevett** [comment]
@Hans0124SG Thanks for posting this - it means a lot to me! Glad people are finding them useful.

**Comment by geekygirl123** [comment]
Same from my side. Its a great tutorial .. also it would be great if you could provide us a tutorial on implementing beam search.
