### ISSUE TITLE
question about tutorial1 Sequence to Sequence Learning with Neural Networks

### ISSUE THREAD

**Issue by possible1402** [bentrevett/pytorch-seq2seq#60]
Dear bentrevett,
Your tutorials are so detailed and it's easier for beginners. I have a question that I can't fix. It's about the loop till max_len. You say that `<eos>` is never input into the decoder. So the code is：`for t in range(1, max_len):`. But if `t` is equal to `max_len-1`,`trg[max_len-1] `will be `<eos>`. I think the code shouble be `for  t in range(1,max_len-1):` But I am new to natural language processing and I'm not sure about that.

**Comment by bentrevett** [comment]
Yes, `<eos>` will be set as `input` for the last iteration of the loop, but it will never be actually input into the decoder as whatever is set as `input` isn't actual put into the model until the following iteration.

An example: `trg = [<sos>, how, are, you, ?, <eos>]`. Therefore, `max_len` is 6 and the loop goes from 1 to 5. Before we go into the loop we first set `input = [<sos>]` with `input = trg[0:]`. Now let's walk through the loop assuming teacher forcing is zero so we will always know what our next input is:

- `t = 1, input (before going into decoder) = <sos>, input (at end of loop) = trg[t] = trg[1] = how`
- `t = 2, input (before going into decoder) = how, input (at end of loop) = trg[t] = trg[2] = are`
- `t = 3, input (before going into decoder) = are, input (at end of loop) = trg[t] = trg[3] = you`
- `t = 4, input (before going into decoder) = you, input (at end of loop) = trg[t] = trg[4] = ?`
- `t = 5, input (before going into decoder) = ?, input (at end of loop) = trg[t] = trg[5] = <eos>`

So, at t = 5, `input` is set to `<eos>`, but it is only set at the very end of the loop and is not ever put into the decoder as that is the last iteration of the loop.

Hopefully that clears things up - let me know if anything needs explaining further.

**Comment by possible1402** [comment]
Thanks!!!
It's clear enough!

**Comment by possible1402** [comment]
Dear bentrevett,
You mention in tutorial 1 that "In the paper we are implementing, they find it beneficial to reverse the order of the input which they believe "introduces many short term dependencies in the data that the optimization problem much easier". Have you published that paper or put on arxiv？If yes, can you provide the name of the paper?

**Comment by bentrevett** [comment]
@possible1402 The paper is found here: https://arxiv.org/abs/1409.3215
