### ISSUE TITLE
packed padded sequences

### ISSUE THREAD

**Issue by possible1402** [bentrevett/pytorch-seq2seq#64]
In pytorch sentiment analysis tutorial 2 Upgraded Sentiment Analysis, you use `packed padded sequences` to avoid that the final hidden state is from a pad token. But in pytorch seq2seq tutorial 1, you don’t use it. Instead, you use `ignore index` when calculatiing loss. Will these two methods get almost same effect?

**Comment by bentrevett** [comment]
`packed_padded_sequences` and the criterion's `ignore_index` do two different things. 

`packed_padded_sequences` are used so you are not wasting computation over `<pad>` tokens within your sequence. 

`ignore_index` is used to avoid calculating loss when the target/label is a `<pad>` token. 

Yes, we can use `packed_padded_sequences` in the seq2seq tutorials. I don't use them in the first 3 tutorials as I wanted to focus on explaining other concepts but they are used in tutorial 4. 

`ignore_index` cannot be used in the sentiment analysis tutorials as it is only really used when your model outputs a sequence and you want to calculate the loss between your output sequence and your target sequence. In the sentiment analysis tutorials we only output a single class prediction, the target/label does not have any padding in it.

**Comment by possible1402** [comment]
Got it! Thank you for your reply!
