### ISSUE TITLE
unk issue

### ISSUE THREAD

**Issue by FrederickXZhang** [bentrevett/pytorch-seq2seq#65]
When I ran tutorial 4 and ran a variation of tutorial 4 since I wanna develop a similar seq2seq model to work on other tasks, I noticed that there wasn't any `<unk>` in translation. It's amazing but also troublesome since we do wanna see some `<unk>`'s in inference and then we can apply some techniques like copy mechanism to boost up the translation quality

**Comment by bentrevett** [comment]
The source and target vocabularies are built with a `min_freq` of 2, so there will be `<unk>` tokens. I am 100% sure I have seen them myself - I'll see if I can find a concrete example.

**Comment by FrederickXZhang** [comment]
You are right, man. I set min_freq to be 1 so there is no `unk` appearing in training or testing
