### ISSUE TITLE
Help needed for transformer encoder only function

### ISSUE THREAD

**Issue by thak123** [bentrevett/pytorch-seq2seq#70]
Hi Ben,
Thanks for the wonderful tutorial series. Based on lesson learnt in the past,
I am trying to encode the src and trg fields into a encoder(transformer) only setting.
But I am facing issues when I create embedding vectors from source and target language as sentence lengths are different. 

Is there a way to create batches such that the but the source and target embedding created have same size.

May be some way to pad them.

**Comment by thak123** [comment]
I found this option called fix_length in the field. I think fixing it would help the cause.

**Comment by bentrevett** [comment]
Why do your sequences need to be the same length?

**Comment by thak123** [comment]
I want to compute the dot product of the two sequences so the output is [batch, seq_len1, hidden_dim] for source as the batch has diff length and  [batch, seq_len2, hidden_dim]  for source sentence. 

But wait I can avg the vectors on the sequence length and get [batch,hidden_dim]. I think I got my answer. I dont think I need fix_length.
