### ISSUE TITLE
Gramatical error in ConvS2S notebook

### ISSUE THREAD

**Issue by M-e-r-c-u-r-y** [bentrevett/pytorch-seq2seq#71]
Thank you for the wonderful series of notebooks :)

This is kinda nitpicking but found a typo so letting you know.
In the intro of [5 - Convolutional Sequence to Sequence Learning notebook](https://github.com/bentrevett/pytorch-seq2seq/blob/master/5%20-%20Convolutional%20Sequence%20to%20Sequence%20Learning.ipynb), the second sentence is "There is are no recurrent components ...". It should be "There are no recurrent components ..."

Suggestion: In [3 - Neural Machine Translation by Jointly Learning to Align and Translate notebook](https://github.com/bentrevett/pytorch-seq2seq/blob/master/3%20-%20Neural%20Machine%20Translation%20by%20Jointly%20Learning%20to%20Align%20and%20Translate.ipynb) you use the nn.Parameter module for defining v in pytorch. I'm assuming this is a shared weight vector that is updated in a back prop through time method like a RNN unit for aligning the decoder with relevant encoder output[t] to produce the next decoded token. I think this info could help beginners understand the paper/ notebook and should be included.

**Comment by bentrevett** [comment]
I've added some more explanation about the v vector. I also noticed it was incorrectly initialized using `rand` (which is uniform between 0 and 1) instead of `randn` (which from a mean 0 Gaussian).

Let me know if the explanations are clearer.

**Comment by M-e-r-c-u-r-y** [comment]
Yep, looks better now.
Although if I think more about it, even the Linear (attn) layer is a shared weight across time so maybe include that as well? Like "We use shared weights (W of the Linear attention layer and the v vector) across all the time steps to compute the energy and attention values" or something along this line.

**Comment by M-e-r-c-u-r-y** [comment]
okay, I redid the Attention class by looking up the exact equation for the attention mlp from the paper and I think I've made it easier to read, the idea is to pass the energy tensor through the a linear layer instead of reshaping the energy tensor, replicating the `v` weights the following way, I've commented out the old code and added the newer bits so that it's easier to compare:
````
class Attention(nn.Module):
    def __init__(self, enc_hid_dim, dec_hid_dim):
        super().__init__()

        
        self.attn = nn.Linear((enc_hid_dim * 2) + dec_hid_dim, dec_hid_dim)
        #self.v = nn.Parameter(torch.randn(dec_hid_dim))
        self.v = nn.Linear(dec_hid_dim,1, bias=False)
        #nn.init.normal_(self.v.weight, mean=0.0, std=1.0)
        #nn.init.zeros_(self.v.weight)
        #print(self.v.weight.shape)
        
    def forward(self, hidden, encoder_outputs):
        
        #hidden = [batch size, dec hid dim]
        #encoder_outputs = [src len, batch size, enc hid dim * 2]
        
        batch_size = encoder_outputs.shape[1]
        src_len = encoder_outputs.shape[0]
        
        #repeat encoder hidden state src_len times
        hidden = hidden.unsqueeze(1).repeat(1, src_len, 1)
        
        encoder_outputs = encoder_outputs.permute(1, 0, 2)
        
        #hidden = [batch size, src len, dec hid dim]
        #encoder_outputs = [batch size, src len, enc hid dim * 2]
        
        energy = torch.tanh(self.attn(torch.cat((hidden, encoder_outputs), dim = 2))) 
        
        #energy = [batch size, src len, dec hid dim]

        """
        
        energy = energy.permute(0, 2, 1)
        
        #energy = [batch size, dec hid dim, src len]
        
        #v = [dec hid dim]
        
        v = self.v.repeat(batch_size, 1).unsqueeze(1)
        
        #v = [batch size, 1, dec hid dim]
                
        attention = torch.bmm(v, energy).squeeze(1)

        """

        attention = self.v(energy).squeeze(2)

        #print(attention.shape)
        
        #attention= [batch size, src len]
        
        return F.softmax(attention, dim=1)
````

Kindly check and see if it's correct and can be incorporated into the code :)

Also I think the weight initialization for `v` vector doesn't matter in the class because later down in the code, `model.apply(init_weights)` is overriding prior initialization.
