### ISSUE TITLE
Help to apply fasttext pre-trining embedding vector. 

### ISSUE THREAD

**Issue by aimanmutasem** [bentrevett/pytorch-seq2seq#72]
Dear Ben,
Thanks for the wonderful tutorial, I'm trying to apply pre-trining embedding vector, and I'm a little confused about how to apply it for (token and position) embedding as below lines of code: 
https://nlp.h-its.org/bpemb/

SRC.build_vocab(train_data, vectors = Vectors('wiki.ar.vec'), min_freq = 2) 
TRG.build_vocab(train_data,  min_freq = 2)

The challenge is how to copy those vectors into the embedding layer.

self.tok_embedding = nn.Embedding(output_dim, emb_dim)
self.pos_embedding = nn.Embedding(100, emb_dim)

I'm looking forward to your kind response.

**Comment by bentrevett** [comment]
The token embedding can be initialized, but the positional embedding cannot.

To initialize the token embeddings for the source vocabulary, you can use the following:

``` python
pretrained_embeddings = SRC.vocab.vectors

model.encoder.tok_embedding.weight.data.copy_(pretrained_embeddings)
```

This has to be done **after** the model has had its weight initialized. If you do it before, then the initialization overwrites the pre-trained embeddings.

I have tried using pre-trained GloVe embeddings for these models in the past and actually found that performance decreased, so let me know if you have any success!

**Comment by bentrevett** [comment]
Also, not sure if you aware, the pre-trained embeddings you linked are for text that has been tokenized with BPE, so your data must also be tokenized with the same BPE.

**Comment by aimanmutasem** [comment]
Thank you, Mr. Ben, for your response. 

When I have tried to apply the embedding the same you mentioned in the previous post. 
```
        self.tok_embedding = nn.Embedding(input_dim, emb_dim)
        self.tok_embedding.weight.data.copy_(p_embeddings)
        self.pos_embedding = nn.Embedding(100, emb_dim)
```
I get an error related to the tensor size as : 
RuntimeError: The expanded size of the tensor (256) must match the existing size (300) at non-singleton dimension 1.  Target sizes: [889, 256].  Tensor sizes: [889, 300]. 

One last question, I have to apply the pre-training for both Encoder and Decoder model, right?

**Comment by bentrevett** [comment]
I believe your error is because your `emb_dim` (256) is not equal to the size of the pre-trained embeddings (300). It looks like those BPE embeddings don't have 256-dimensional pre-trained embeddings, so you can fix this by changing `emb_dim` to 300.  

You can apply the pre-trained embeddings to just one of the Encoder or Decoder, or both. I believe applying it to both will lead to better results, but I have not tested it.

**Comment by aimanmutasem** [comment]
Dear Ben,

I have spent the last few hours trying to apply fasttext pre-trining embedding. You are right, in my case the performance doing down. 
On the other hand, many papers reported that pre-training embedding improves performance. I think we have an implementation issue. Also, when I tried to apply pre-training for Encoder and decoder I get an error as below: 

`RuntimeError: The expanded size of the tensor (868) must match the existing size (846) at non-singleton dimension 0.  Target sizes: [868, 300].  Tensor sizes: [846, 300]
`
Now, it works for the encoder, I hope to collaborate together to fix this issue.  

Regards, 
Aiman

**Comment by bentrevett** [comment]
Pre-trained embeddings do usually improve model performance in NLP tasks, yes. But I've noticed that most translation tasks using neural networks do not use pre-trained embeddings. 

Methods like BERT can be used as pre-trained embeddings, but this uses a whole pre-trained model and not just the embedding layer. So potentially the method in which pre-trained embeddings are learned (usually language modeling) is not a good fit for translation tasks? I'll admit I don't fully understand why and haven't seen any research into this either.

I'm not sure why you are getting a size mismatch error, your vocabulary size doesn't seem to be matching the size of the pre-trained embeddings, even though your last comment 2 days ago had them both be the same size (889) and just not matching in the embedding dimension.

**Comment by aimanmutasem** [comment]
Thank you Ben, 

Firstly, I use convolutional seq2seq with NMT for automatic grammar error correction task.  
The first paper used convolutional seq2seq for GEC in 2018 mentions that pretraining embedding improves the final results. please check the below link : 
https://arxiv.org/pdf/1801.08831v1.pdf .

For the matching the size error, I will try to fix it soon :) 

![Fasttext](https://user-images.githubusercontent.com/7637767/73509683-f21c4980-441a-11ea-8381-2d03039d6459.png)

**Comment by aimanmutasem** [comment]
Dear Ben, 

It works with me now. without any change, the training loss is decreased slow, so I have increased the number of epochs, and F1 score improved from 78.49% to 79.81%.

Thanks so much :)

**Comment by winsapdev** [comment]
> Dear Ben,
> 
> It works with me now. without any change, the training loss is decreased slow, so I have increased the number of epochs, and F1 score improved from 78.49% to 79.81%.
> 
> Thanks so much :)

Dear @aimanmutasem 

Can you provide the sourcecode from your work please? I am currently struggling about to apply pretrained embedding in seq2seq based on Transformer.
Thank you very much

Regards,
Winsap

**Comment by aimanmutasem** [comment]
Hello @winsapdev 

This post was a long time ago, actually I don't have to source code. Please, try to use the following lines may it will help: 

```
SRC.build_vocab(train_data, vectors = Vectors('wiki.ar.vec'), min_freq = 2)
TRG.build_vocab(train_data, min_freq = 2)

self.tok_embedding = nn.Embedding(output_dim, emb_dim)
self.pos_embedding = nn.Embedding(300, emb_dim)
```

Please make sure that you use 300 for model dimension.
