### ISSUE TITLE
Packed Padded Sequences

### ISSUE THREAD

**Issue by dariodematties** [bentrevett/pytorch-seq2seq#79]
Hi, first of all, thank you very much for this great contribution.

In the tutorial number 4, In the Encoder module forward function the argument src_len is specified in the following way:
#src_len = [src len]
Shouldn't it be #src_len = [batch size] ?
As far as I understand src_len is a vector containing the length of each sentence in the batch, isn't it?

Thanks!!

**Comment by bentrevett** [comment]
@dariodematties Yep, you're correct! That's a typo on my end. Will fix shortly. Thanks for spotting.
