### ISSUE TITLE
Applying BERT pre-training

### ISSUE THREAD

**Issue by aimanmutasem** [bentrevett/pytorch-seq2seq#81]
Dear Ben,

I have an idea to use BERT preparing embedding with your code (dynamic embedding) instead of Fasttext embedding, but I little confused about how to load and pass the BERT vectors to the model. 

Kindly, I need your guidance, the blown article encourage me to do this.   
https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/

Thank you a lot

**Comment by bentrevett** [comment]
I have a tutorial showing how to use the HuggingFace Transformer's pre-trained BERT model for sentiment analysis. This should give you a good starting off point and hopefully show you how to use them for translation: https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/6%20-%20Transformers%20for%20Sentiment%20Analysis.ipynb

**Comment by aimanmutasem** [comment]
Thank you so much Ben :)
