### ISSUE TITLE
Tutorial - 4 How to apply pretrained embedding and initial hidden state

### ISSUE THREAD

**Issue by rishab-32** [bentrevett/pytorch-seq2seq#82]
Hi Ben, thanks a lot for the comprehensively explained tutorials.

I was wondering how can I use my pre-trained embeddings to initialize embedding for Encoder and Decoder in Tutorial-4. 

I am using Language model to extract the embedding for each token. However I am not able to figure out how can I assign these pretrained embedding in encoder and decoder. 

Also I want to feed my custom pretrained as initial hidden state of Encoder, which I have learned for each separate input sentence.

It would be really helpful if you could help me with this.

**Comment by bentrevett** [comment]
I have a tutorial on how to load custom embeddings with TorchText for use in sentiment analysis: https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/C%20-%20Loading%2C%20Saving%20and%20Freezing%20Embeddings.ipynb

You basically need to take your language model and save all of the embedding layer parameters to a text file in the format TorchText wants and then load them up using `vocab.Vectors`, then you can pass them to the `build_vocab` function. 

Let me know if you need anymore help.

**Comment by rishab-32** [comment]
Hi, Ben thanks for the help.

Also, how can I set the first hidden state to pretrained tensor I have?

**Comment by rishab-32** [comment]
One more question, do all the embeddings has to be in the txt file has to be in the same order as that of the word2index dictionary (this is a kind of requirement in Tensorflow)?

**Comment by bentrevett** [comment]
> Also, how can I set the first hidden state to pretrained tensor I have?

Is this the same initial state for every single example? I believe you'll have to load it as a numpy array and then convert it into a PyTorch nn.Parameter and set it as an attribute of your model, i.e. `model.initial_hidden`.

> One more question, do all the embeddings has to be in the txt file has to be in the same order as that of the word2index dictionary (this is a kind of requirement in Tensorflow)?

No. When you do `build_vocab` and pass in a `vectors`, it will make sure the vectors match up with the vocabulary it creates from your dataset.

**Comment by rishab-32** [comment]
The pre-trained initial hidden states are different for each document. Then how would the model be able to map each document in a batch to its initial hidden state?



Also is the following code correct?

def init_weights(m):
    for name, param in m.named_parameters():
        if 'weight' in name:
            nn.init.normal_(param.data, mean=0, std=0.01)
        else:
            nn.init.constant_(param.data, 0)
            
model.apply(init_weights)

embeddings_src = SRC.vocab.vectors
model.encoder.embedding.weight.data.copy_(embeddings_src)

embeddings_trg = TRG.vocab.vectors
model.decoder.embedding.weight.data.copy_(embeddings_trg)

**Comment by bentrevett** [comment]
Yes, that code looks correct.

When you say initial hidden state, do you mean your h_0, the hidden state before any input (src/trg) has been seen? 

If so, I don't think having an initial hidden state per document is correct. This initial hidden state should not depend on what the input sequence is because it shouldn't have seen it yet. Your pretrained initial hidden state should, in theory, just be a better starting off point than having an initial hidden state of all zeros, but again, should **not** depend on the document, it should be for **all documents**.

What is the task you are trying to do?

**Comment by rishab-32** [comment]
Yes I mean h_0 and you are right and I understand having different h_0 for each document does not seem right. I am working on the text summarization and your tutorials have been really helpful till now. Thanks a lot for your contribution and patience.

I would definitely contact you again if I encounter any other problem, I hope you don't mind and thanks a lot again.
