### ISSUE TITLE
What is `seq_len` in Transformers notebook?

### ISSUE THREAD

**Issue by kushalj001** [bentrevett/pytorch-seq2seq#83]
![image](https://user-images.githubusercontent.com/32245327/76527680-a3d87c80-6495-11ea-8266-4c198b5dfb17.png)

Here the shape of energy is given as `[batch size, n heads, seq len, seq len]`. However, given the previous computation, it should simply be `[batch size, n heads, query_len, key len]`. What is the `seq_len` for? What does it mean? 
Also, how do we arrive at the dimensions of x as `[batch size, n heads, seq len, head dim]`  by multiplication of attention vector and V?
Thank you.

**Comment by bentrevett** [comment]
You're correct. It should be query and key lengths. Not sure why it became seq length. Looks like I forgot to finish off the comments, will do now.

For calculating x, we have the following tensors:
`attention = [batch, n heads, query len, key len]`
`v = [batch, n heads, value len, head dim]`

In our implementation, key len and value len are always the same.

When using `torch.matmul` on two tensors that are both >2-dimensional it will just do a batched matrix multiplication over the last two dimensions of each tensor, thus it will do a matrix multiplication between `[query len, key len] x [value len, head dim]`. As mention above, key and value len are always the same so this matrix multiplication is always valid, giving us an output of `[query len, head dim]` and this is over all of the batch size and n heads dimensions, thus we get a tensor of size `[batch size, n heads, query len, head dim]`.
