### ISSUE TITLE
Typo in notebook 5 ?

### ISSUE THREAD

**Issue by garychl** [bentrevett/pytorch-seq2seq#87]
In the notebook:

 
`This is because the convolutional layers will reduce the length of the input sentence and we want the length of the sentence coming into the convolutional blocks to equal the length of it coming`  **into** `the convolutional blocks.`

I think it should be **coming out of** the convolutional blocks instead of coming **into**, right?

---

`Let's see what happens if we incorrectly padded equally on each side, like we do in the` **decoder**.
I think it should be **encoder** instead of **decoder**, right?

---
Thanks for the awesome tutorials anyways!

**Comment by bentrevett** [comment]
Thanks for spotting these, and for the kind words.
