### ISSUE TITLE
beam search

### ISSUE THREAD

**Issue by wangleiai** [bentrevett/pytorch-seq2seq#93]
Hi!
Thanks for  your project ,I have gained  a lot from it. But I just ask you that do you ready to implement beam search?
I have implemented a version beam search ,but it performs worse than greedy search, so I want to know your version.
@bentrevett

**Comment by wangleiai** [comment]
I have implemented a version beam search ,but it performs worse than greedy search, so I want to know your version.

**Comment by bentrevett** [comment]
Beam search is something I am planning to implement when I get the time.
