### ISSUE TITLE
[Tutorial 3] Minor typo on bidirectional GRU definition

### ISSUE THREAD

**Issue by dataframing** [bentrevett/pytorch-seq2seq#97]
Hi Ben,

First of all, thank you so much for these tutorials — they're incredibly well-written and accessible!  I think there's a typo in tutorial 3, however, specifically in the formalization of the bidirectional GRU. Specifically, the notebook says:

<img width="242" alt="Screen Shot 2020-04-15 at 21 27 55" src="https://user-images.githubusercontent.com/8692129/79414652-0bd02600-7f60-11ea-8e0e-594901c4072c.png">

instead of:

<img width="235" alt="Screen Shot 2020-04-15 at 21 27 59" src="https://user-images.githubusercontent.com/8692129/79414670-138fca80-7f60-11ea-9131-9efc87ce6999.png">

Happy to open a PR for this, if you're busy. Thanks again!

**Comment by bentrevett** [comment]
Thanks for the kind words, nice find on the typo! Should be fixed now.
